/**
 * js/data-vocab-a.js - 词汇积累 Day 1-10（200 词）
 * 每词：en 单词 / ph 美式音标 / defs 全部词性词义 / ex 例句 / ec 例句翻译
 * 四个中文选项由 vocab.js 运行时生成（正确项 + 3 个干扰项，顺序打乱）。
 */

const VOCAB_PART_A = {
  1: { // Day1 问候与自我介绍
    topic: '问候与自我介绍',
    words: [
      { en: 'greet', ph: '/ɡriːt/', defs: [{ p: 'v.', c: '问候；迎接' }], ex: 'She greeted us warmly at the door.', ec: '她在门口热情地迎接了我们。' },
      { en: 'introduce', ph: '/ˌɪntrəˈduːs/', defs: [{ p: 'v.', c: '介绍；引见' }], ex: 'Let me introduce myself.', ec: '让我自我介绍一下。' },
      { en: 'pleasure', ph: '/ˈpleʒər/', defs: [{ p: 'n.', c: '愉快；荣幸' }], ex: 'It is a pleasure to meet you.', ec: '见到你很高兴。' },
      { en: 'familiar', ph: '/fəˈmɪliər/', defs: [{ p: 'adj.', c: '熟悉的；常见的' }], ex: 'Your face looks familiar to me.', ec: '我看你有点面熟。' },
      { en: 'abroad', ph: '/əˈbrɔːd/', defs: [{ p: 'adv.', c: '在国外；到国外' }], ex: 'She has never been abroad.', ec: '她从没出过国。' },
      { en: 'stranger', ph: '/ˈstreɪndʒər/', defs: [{ p: 'n.', c: '陌生人' }], ex: 'Never talk to a stranger alone.', ec: '不要单独和陌生人交谈。' },
      { en: 'polite', ph: '/pəˈlaɪt/', defs: [{ p: 'adj.', c: '有礼貌的；客气的' }], ex: 'It is polite to say thank you.', ec: '说谢谢是有礼貌的表现。' },
      { en: 'acquaintance', ph: '/əˈkweɪntəns/', defs: [{ p: 'n.', c: '熟人；认识的人' }], ex: 'He is just an acquaintance of mine.', ec: '他只是我的一个熟人。' },
      { en: 'surname', ph: '/ˈsɜːrneɪm/', defs: [{ p: 'n.', c: '姓；姓氏' }], ex: 'Please write your surname here.', ec: '请在这里写下你的姓。' },
      { en: 'culture', ph: '/ˈkʌltʃər/', defs: [{ p: 'n.', c: '文化；文明' }], ex: 'I am interested in Chinese culture.', ec: '我对中国文化很感兴趣。' },
      { en: 'custom', ph: '/ˈkʌstəm/', defs: [{ p: 'n.', c: '风俗；习惯' }], ex: 'It is a local custom to greet first.', ec: '先打招呼是当地的风俗。' },
      { en: 'hometown', ph: '/ˈhoʊmtaʊn/', defs: [{ p: 'n.', c: '家乡；故乡' }], ex: 'My hometown is a small town.', ec: '我的家乡是个小镇。' },
      { en: 'guest', ph: '/ɡest/', defs: [{ p: 'n.', c: '客人；宾客' }], ex: 'We have a guest for dinner tonight.', ec: '今晚我们有客人来吃饭。' },
      { en: 'host', ph: '/hoʊst/', defs: [{ p: 'n.', c: '主人；东道主' }, { p: 'v.', c: '主办；招待' }], ex: 'Our host welcomed us with a smile.', ec: '主人微笑着欢迎我们。' },
      { en: 'welcome', ph: '/ˈwelkəm/', defs: [{ p: 'v.', c: '欢迎' }, { p: 'adj.', c: '受欢迎的' }], ex: 'Welcome to our city!', ec: '欢迎来到我们的城市！' },
      { en: 'traveler', ph: '/ˈtrævələr/', defs: [{ p: 'n.', c: '旅行者；旅客' }], ex: 'Many travelers visit here in summer.', ec: '夏天有很多游客来这里。' },
      { en: 'exchange', ph: '/ɪksˈtʃeɪndʒ/', defs: [{ p: 'v.', c: '交换；兑换' }, { p: 'n.', c: '交换' }], ex: 'We exchanged phone numbers.', ec: '我们交换了电话号码。' },
      { en: 'mutual', ph: '/ˈmjuːtʃuəl/', defs: [{ p: 'adj.', c: '相互的；共同的' }], ex: 'We have a mutual friend.', ec: '我们有一个共同的朋友。' },
      { en: 'nation', ph: '/ˈneɪʃn/', defs: [{ p: 'n.', c: '国家；民族' }], ex: 'China is a great nation.', ec: '中国是一个伟大的国家。' },
      { en: 'local', ph: '/ˈloʊkl/', defs: [{ p: 'adj.', c: '当地的；本地的' }, { p: 'n.', c: '本地人' }], ex: 'Ask a local for directions.', ec: '找个本地人问问路。' }
    ]
  },
  2: { // Day2 餐厅点餐
    topic: '餐厅点餐',
    words: [
      { en: 'menu', ph: '/ˈmenjuː/', defs: [{ p: 'n.', c: '菜单' }], ex: 'Could I see the menu, please?', ec: '请给我看看菜单。' },
      { en: 'appetizer', ph: '/ˈæpɪtaɪzər/', defs: [{ p: 'n.', c: '开胃菜；前菜' }], ex: 'We ordered two appetizers first.', ec: '我们先点了两道开胃菜。' },
      { en: 'cuisine', ph: '/kwɪˈziːn/', defs: [{ p: 'n.', c: '菜肴；烹饪风格' }], ex: 'French cuisine is world famous.', ec: '法国菜世界闻名。' },
      { en: 'beverage', ph: '/ˈbevərɪdʒ/', defs: [{ p: 'n.', c: '饮料' }], ex: 'Would you like any beverage?', ec: '你想喝点什么饮料吗？' },
      { en: 'dessert', ph: '/dɪˈzɜːrt/', defs: [{ p: 'n.', c: '甜点；甜品' }], ex: 'We shared a dessert after dinner.', ec: '晚饭后我们分了一份甜点。' },
      { en: 'order', ph: '/ˈɔːrdər/', defs: [{ p: 'v.', c: '点餐；订购' }, { p: 'n.', c: '订单；顺序' }], ex: 'Are you ready to order?', ec: '您准备好点餐了吗？' },
      { en: 'taste', ph: '/teɪst/', defs: [{ p: 'v.', c: '品尝' }, { p: 'n.', c: '味道；口味' }], ex: 'Would you like to taste it?', ec: '你想尝一尝吗？' },
      { en: 'delicious', ph: '/dɪˈlɪʃəs/', defs: [{ p: 'adj.', c: '美味的；可口的' }], ex: 'The soup is really delicious.', ec: '这汤真好喝。' },
      { en: 'spicy', ph: '/ˈspaɪsi/', defs: [{ p: 'adj.', c: '辣的；辛辣的' }], ex: 'I like spicy Sichuan food.', ec: '我喜欢辣的川菜。' },
      { en: 'fresh', ph: '/freʃ/', defs: [{ p: 'adj.', c: '新鲜的' }], ex: 'The vegetables are fresh today.', ec: '今天的蔬菜很新鲜。' },
      { en: 'serve', ph: '/sɜːrv/', defs: [{ p: 'v.', c: '上菜；服务' }], ex: 'They serve breakfast until ten.', ec: '他们早餐供应到十点。' },
      { en: 'waiter', ph: '/ˈweɪtər/', defs: [{ p: 'n.', c: '服务员（男）' }], ex: 'The waiter brought us the menu.', ec: '服务员给我们拿来了菜单。' },
      { en: 'dish', ph: '/dɪʃ/', defs: [{ p: 'n.', c: '菜肴；盘子' }], ex: 'This dish is their signature.', ec: '这道菜是他们的招牌。' },
      { en: 'soup', ph: '/suːp/', defs: [{ p: 'n.', c: '汤' }], ex: 'A bowl of hot soup, please.', ec: '请来一碗热汤。' },
      { en: 'salad', ph: '/ˈsæləd/', defs: [{ p: 'n.', c: '沙拉；凉拌菜' }], ex: 'I will have a green salad.', ec: '我要一份蔬菜沙拉。' },
      { en: 'sauce', ph: '/sɔːs/', defs: [{ p: 'n.', c: '酱汁；调味汁' }], ex: 'This chicken goes well with sauce.', ec: '这个鸡肉配酱汁很好吃。' },
      { en: 'main', ph: '/meɪn/', defs: [{ p: 'adj.', c: '主要的' }, { p: 'n.', c: '主菜' }], ex: 'What is the main course today?', ec: '今天的主菜是什么？' },
      { en: 'fork', ph: '/fɔːrk/', defs: [{ p: 'n.', c: '叉子' }], ex: 'He eats noodles with a fork.', ec: '他用叉子吃面条。' },
      { en: 'knife', ph: '/naɪf/', defs: [{ p: 'n.', c: '刀' }], ex: 'The knife is on the right.', ec: '刀在右手边。' },
      { en: 'plate', ph: '/pleɪt/', defs: [{ p: 'n.', c: '盘子' }], ex: 'The waiter took away the empty plates.', ec: '服务员收走了空盘子。' }
    ]
  },
  3: { // Day3 酒店住宿
    topic: '酒店住宿',
    words: [
      { en: 'reserve', ph: '/rɪˈzɜːrv/', defs: [{ p: 'v.', c: '预订；保留' }], ex: 'I reserved a room for two nights.', ec: '我订了两晚的房间。' },
      { en: 'lobby', ph: '/ˈlɑːbi/', defs: [{ p: 'n.', c: '大堂；门厅' }], ex: 'Let us meet in the hotel lobby.', ec: '我们在酒店大堂见吧。' },
      { en: 'suite', ph: '/swiːt/', defs: [{ p: 'n.', c: '套房' }], ex: 'They stayed in a corner suite.', ec: '他们住在一间角落套房。' },
      { en: 'housekeeping', ph: '/ˈhaʊskiːpɪŋ/', defs: [{ p: 'n.', c: '客房服务；家政' }], ex: 'Please call housekeeping for towels.', ec: '请给客房服务打电话要毛巾。' },
      { en: 'deposit', ph: '/dɪˈpɑːzɪt/', defs: [{ p: 'n.', c: '押金；存款' }], ex: 'A deposit is needed when checking in.', ec: '入住时需要交押金。' },
      { en: 'reception', ph: '/rɪˈsepʃn/', defs: [{ p: 'n.', c: '前台；接待处' }], ex: 'Go to the reception to check in.', ec: '去前台办理入住。' },
      { en: 'checkout', ph: '/ˈtʃekaʊt/', defs: [{ p: 'n.', c: '退房；结账' }], ex: 'Checkout time is twelve noon.', ec: '退房时间是中午十二点。' },
      { en: 'keycard', ph: '/ˈkiːkɑːrd/', defs: [{ p: 'n.', c: '房卡' }], ex: 'Use your keycard to open the door.', ec: '用你的房卡开门。' },
      { en: 'vacancy', ph: '/ˈveɪkənsi/', defs: [{ p: 'n.', c: '空房；空缺' }], ex: 'Sorry, we have no vacancy tonight.', ec: '抱歉，我们今晚没有空房了。' },
      { en: 'laundry', ph: '/ˈlɔːndri/', defs: [{ p: 'n.', c: '洗衣；待洗衣物' }], ex: 'Is there a laundry service?', ec: '有洗衣服务吗？' },
      { en: 'luggage', ph: '/ˈlʌɡɪdʒ/', defs: [{ p: 'n.', c: '行李' }], ex: 'I left my luggage at the desk.', ec: '我把行李寄存在前台了。' },
      { en: 'elevator', ph: '/ˈelɪveɪtər/', defs: [{ p: 'n.', c: '电梯' }], ex: 'Take the elevator to the fifth floor.', ec: '坐电梯到五楼。' },
      { en: 'corridor', ph: '/ˈkɔːrɪdɔːr/', defs: [{ p: 'n.', c: '走廊；通道' }], ex: 'Our room is at the end of the corridor.', ec: '我们的房间在走廊尽头。' },
      { en: 'pillow', ph: '/ˈpɪloʊ/', defs: [{ p: 'n.', c: '枕头' }], ex: 'Could I have an extra pillow?', ec: '能再给我一个枕头吗？' },
      { en: 'towel', ph: '/ˈtaʊəl/', defs: [{ p: 'n.', c: '毛巾' }], ex: 'Please change the towels daily.', ec: '请每天更换毛巾。' },
      { en: 'blanket', ph: '/ˈblæŋkɪt/', defs: [{ p: 'n.', c: '毯子；毛毯' }], ex: 'The blanket is a bit thin.', ec: '毯子有点薄。' },
      { en: 'bathroom', ph: '/ˈbæθruːm/', defs: [{ p: 'n.', c: '浴室；卫生间' }], ex: 'The bathroom is very clean.', ec: '浴室非常干净。' },
      { en: 'wifi', ph: '/ˈwaɪfaɪ/', defs: [{ p: 'n.', c: '无线网络' }], ex: 'The wifi password is on the card.', ec: '无线网密码在卡片上。' },
      { en: 'front', ph: '/frʌnt/', defs: [{ p: 'adj.', c: '前面的' }, { p: 'n.', c: '前面' }], ex: 'The front desk is over there.', ec: '前台在那边。' },
      { en: 'quiet', ph: '/ˈkwaɪət/', defs: [{ p: 'adj.', c: '安静的' }], ex: 'We asked for a quiet room.', ec: '我们要了一间安静的房间。' }
    ]
  },
  4: { // Day4 交通出行
    topic: '交通出行',
    words: [
      { en: 'terminal', ph: '/ˈtɜːrmɪnl/', defs: [{ p: 'n.', c: '航站楼；终点站' }], ex: 'My flight leaves from Terminal 2.', ec: '我的航班从 2 号航站楼起飞。' },
      { en: 'platform', ph: '/ˈplætfɔːrm/', defs: [{ p: 'n.', c: '站台；平台' }], ex: 'The train leaves from Platform 3.', ec: '火车从 3 号站台发车。' },
      { en: 'depart', ph: '/dɪˈpɑːrt/', defs: [{ p: 'v.', c: '出发；离开' }], ex: 'The bus departs at nine sharp.', ec: '公交车九点整出发。' },
      { en: 'arrive', ph: '/əˈraɪv/', defs: [{ p: 'v.', c: '到达；抵达' }], ex: 'We will arrive at the hotel soon.', ec: '我们很快就到酒店了。' },
      { en: 'transfer', ph: '/trænsˈfɜːr/', defs: [{ p: 'v.', c: '换乘；转移' }], ex: 'Transfer to Line 2 at the next stop.', ec: '下一站换乘 2 号线。' },
      { en: 'vehicle', ph: '/ˈviːəkl/', defs: [{ p: 'n.', c: '车辆；交通工具' }], ex: 'Parking for large vehicles is outside.', ec: '大车停在外面。' },
      { en: 'passenger', ph: '/ˈpæsɪndʒər/', defs: [{ p: 'n.', c: '乘客；旅客' }], ex: 'All passengers must show tickets.', ec: '所有乘客都必须出示车票。' },
      { en: 'route', ph: '/ruːt/', defs: [{ p: 'n.', c: '路线；线路' }], ex: 'This bus takes a long route.', ec: '这趟公交车走的路线很长。' },
      { en: 'ticket', ph: '/ˈtɪkɪt/', defs: [{ p: 'n.', c: '车票；门票' }], ex: 'I bought two tickets online.', ec: '我在网上买了两张票。' },
      { en: 'subway', ph: '/ˈsʌbweɪ/', defs: [{ p: 'n.', c: '地铁' }], ex: 'The subway is faster than the bus.', ec: '地铁比公交车快。' },
      { en: 'station', ph: '/ˈsteɪʃn/', defs: [{ p: 'n.', c: '车站；站' }], ex: 'The station is two blocks away.', ec: '车站在两个街区外。' },
      { en: 'stop', ph: '/stɑːp/', defs: [{ p: 'n.', c: '站点；停车站' }, { p: 'v.', c: '停止' }], ex: 'Get off at the third stop.', ec: '在第三站下车。' },
      { en: 'fare', ph: '/fer/', defs: [{ p: 'n.', c: '车费；票价' }], ex: 'The bus fare is two dollars.', ec: '公交车费是两美元。' },
      { en: 'schedule', ph: '/ˈskedʒuːl/', defs: [{ p: 'n.', c: '时刻表；日程安排' }], ex: 'Check the train schedule online.', ec: '在网上查一下火车时刻表。' },
      { en: 'delay', ph: '/dɪˈleɪ/', defs: [{ p: 'v.', c: '延误；推迟' }, { p: 'n.', c: '延误' }], ex: 'The flight was delayed by an hour.', ec: '航班延误了一小时。' },
      { en: 'entrance', ph: '/ˈentrəns/', defs: [{ p: 'n.', c: '入口' }], ex: 'Meet me at the main entrance.', ec: '在大门口等我。' },
      { en: 'exit', ph: '/ˈeksɪt/', defs: [{ p: 'n.', c: '出口' }], ex: 'Take Exit B to the left.', ec: '从左边的 B 出口出。' },
      { en: 'lane', ph: '/leɪn/', defs: [{ p: 'n.', c: '车道；小路' }], ex: 'Stay in the left lane.', ec: '保持在左侧车道。' },
      { en: 'crossroad', ph: '/ˈkrɔːsroʊd/', defs: [{ p: 'n.', c: '十字路口' }], ex: 'Turn right at the crossroad.', ec: '在十字路口右转。' },
      { en: 'pedestrian', ph: '/pəˈdestriən/', defs: [{ p: 'n.', c: '行人' }], ex: 'The car stopped for pedestrians.', ec: '汽车停下来让行人先过。' }
    ]
  },
  5: { // Day5 机场与航班
    topic: '机场与航班',
    words: [
      { en: 'flight', ph: '/flaɪt/', defs: [{ p: 'n.', c: '航班；飞行' }], ex: 'My flight takes off at eight.', ec: '我的航班八点起飞。' },
      { en: 'boarding', ph: '/ˈbɔːrdɪŋ/', defs: [{ p: 'n.', c: '登机' }], ex: 'Boarding begins thirty minutes early.', ec: '提前三十分钟开始登机。' },
      { en: 'customs', ph: '/ˈkʌstəmz/', defs: [{ p: 'n.', c: '海关' }], ex: 'We passed through customs quickly.', ec: '我们很快就通过了海关。' },
      { en: 'declare', ph: '/dɪˈkler/', defs: [{ p: 'v.', c: '申报；声明' }], ex: 'Do you have anything to declare?', ec: '你有什么要申报的吗？' },
      { en: 'gate', ph: '/ɡeɪt/', defs: [{ p: 'n.', c: '登机口；大门' }], ex: 'Gate 12 is at the end of the hall.', ec: '12 号登机口在大厅尽头。' },
      { en: 'seatbelt', ph: '/ˈsiːtbelt/', defs: [{ p: 'n.', c: '安全带' }], ex: 'Please fasten your seatbelt.', ec: '请系好安全带。' },
      { en: 'cabin', ph: '/ˈkæbɪn/', defs: [{ p: 'n.', c: '客舱；机舱' }], ex: 'The cabin is quiet and clean.', ec: '客舱安静又干净。' },
      { en: 'aisle', ph: '/aɪl/', defs: [{ p: 'n.', c: '过道；通道' }], ex: 'Could I have an aisle seat?', ec: '能给我一个靠过道的座位吗？' },
      { en: 'pilot', ph: '/ˈpaɪlət/', defs: [{ p: 'n.', c: '飞行员' }], ex: 'The pilot welcomed us on board.', ec: '飞行员在机上欢迎我们。' },
      { en: 'crew', ph: '/kruː/', defs: [{ p: 'n.', c: '机组人员；全体船员' }], ex: 'The crew is very professional.', ec: '机组人员非常专业。' },
      { en: 'landing', ph: '/ˈlændɪŋ/', defs: [{ p: 'n.', c: '降落；着陆' }], ex: 'The landing was smooth.', ec: '降落得很平稳。' },
      { en: 'takeoff', ph: '/ˈteɪkɔːf/', defs: [{ p: 'n.', c: '起飞' }], ex: 'The takeoff was delayed by fog.', ec: '因大雾起飞延误了。' },
      { en: 'baggage', ph: '/ˈbæɡɪdʒ/', defs: [{ p: 'n.', c: '行李（美式）' }], ex: 'My baggage arrived on time.', ec: '我的行李准时到了。' },
      { en: 'checkin', ph: '/ˈtʃekɪn/', defs: [{ p: 'n.', c: '值机；办理登机手续' }], ex: 'Check-in opens two hours early.', ec: '提前两小时开始值机。' },
      { en: 'security', ph: '/sɪˈkjʊrəti/', defs: [{ p: 'n.', c: '安检；安全' }], ex: 'Security took about twenty minutes.', ec: '安检花了大约二十分钟。' },
      { en: 'departure', ph: '/dɪˈpɑːrtʃər/', defs: [{ p: 'n.', c: '出发；离港' }], ex: 'The departure lounge is upstairs.', ec: '出发候机厅在楼上。' },
      { en: 'arrival', ph: '/əˈraɪvl/', defs: [{ p: 'n.', c: '到达；抵达' }], ex: 'The arrival time is shown on the board.', ec: '到达时间显示在屏幕上。' },
      { en: 'overhead', ph: '/ˌoʊvərˈhed/', defs: [{ p: 'adj.', c: '头顶上的' }, { p: 'n.', c: '行李架' }], ex: 'Put your bag in the overhead bin.', ec: '把你的包放在头顶行李架上。' },
      { en: 'luggage', ph: '/ˈlʌɡɪdʒ/', defs: [{ p: 'n.', c: '行李（英式）' }], ex: 'I have two pieces of luggage.', ec: '我有两件行李。' },
      { en: 'airline', ph: '/ˈerlaɪn/', defs: [{ p: 'n.', c: '航空公司' }], ex: 'Which airline are you flying?', ec: '你坐哪家航空公司的飞机？' }
    ]
  },
  6: { // Day6 购物消费
    topic: '购物消费',
    words: [
      { en: 'purchase', ph: '/ˈpɜːrtʃəs/', defs: [{ p: 'v.', c: '购买' }, { p: 'n.', c: '购买；购置物' }], ex: 'I purchased this online yesterday.', ec: '我昨天在网上买了这个。' },
      { en: 'discount', ph: '/ˈdɪskaʊnt/', defs: [{ p: 'n.', c: '折扣' }], ex: 'Members get a ten percent discount.', ec: '会员打九折。' },
      { en: 'refund', ph: '/ˈriːfʌnd/', defs: [{ p: 'n.', c: '退款' }, { p: 'v.', c: '退款；偿还' }], ex: 'I asked for a full refund.', ec: '我要求全额退款。' },
      { en: 'receipt', ph: '/rɪˈsiːt/', defs: [{ p: 'n.', c: '收据；小票' }], ex: 'Keep the receipt for returns.', ec: '保留收据以便退换。' },
      { en: 'bargain', ph: '/ˈbɑːrɡən/', defs: [{ p: 'v.', c: '讨价还价' }, { p: 'n.', c: '便宜货' }], ex: 'You can bargain at the market.', ec: '在市场上可以砍价。' },
      { en: 'cashier', ph: '/kæˈʃɪr/', defs: [{ p: 'n.', c: '收银员' }], ex: 'The cashier gave me the change.', ec: '收银员找了我零钱。' },
      { en: 'counter', ph: '/ˈkaʊntər/', defs: [{ p: 'n.', c: '柜台；吧台' }], ex: 'Pay at the counter over there.', ec: '在那边柜台付款。' },
      { en: 'brand', ph: '/brænd/', defs: [{ p: 'n.', c: '品牌' }], ex: 'This is a famous international brand.', ec: '这是一个著名的国际品牌。' },
      { en: 'price', ph: '/praɪs/', defs: [{ p: 'n.', c: '价格；价钱' }], ex: 'The price includes tax.', ec: '这个价格含税。' },
      { en: 'expensive', ph: '/ɪkˈspensɪv/', defs: [{ p: 'adj.', c: '昂贵的' }], ex: 'This hotel is too expensive.', ec: '这家酒店太贵了。' },
      { en: 'cheap', ph: '/tʃiːp/', defs: [{ p: 'adj.', c: '便宜的' }], ex: 'The food here is cheap and good.', ec: '这里的食物又便宜又好。' },
      { en: 'free', ph: '/friː/', defs: [{ p: 'adj.', c: '免费的；自由的' }], ex: 'The museum is free on Mondays.', ec: '博物馆周一免费开放。' },
      { en: 'sample', ph: '/ˈsæmpl/', defs: [{ p: 'n.', c: '样品；试用品' }], ex: 'Would you like a free sample?', ec: '你想要个免费试用装吗？' },
      { en: 'wrap', ph: '/ræp/', defs: [{ p: 'v.', c: '包装；包裹' }], ex: 'Could you wrap this as a gift?', ec: '能把这个包成礼物吗？' },
      { en: 'exchange', ph: '/ɪksˈtʃeɪndʒ/', defs: [{ p: 'v.', c: '换货；兑换' }], ex: 'Can I exchange this for another?', ec: '我能换一个吗？' },
      { en: 'quality', ph: '/ˈkwɑːləti/', defs: [{ p: 'n.', c: '质量；品质' }], ex: 'The quality is excellent.', ec: '质量非常好。' },
      { en: 'market', ph: '/ˈmɑːrkɪt/', defs: [{ p: 'n.', c: '市场；集市' }], ex: 'The night market is crowded.', ec: '夜市很热闹。' },
      { en: 'mall', ph: '/mɔːl/', defs: [{ p: 'n.', c: '购物中心；商场' }], ex: 'The mall is open until ten.', ec: '商场营业到十点。' },
      { en: 'shop', ph: '/ʃɑːp/', defs: [{ p: 'n.', c: '商店' }, { p: 'v.', c: '购物' }], ex: 'The gift shop is on the first floor.', ec: '礼品店在一楼。' },
      { en: 'sale', ph: '/seɪl/', defs: [{ p: 'n.', c: '促销；减价' }], ex: 'Everything is on sale today.', ec: '今天所有商品都在打折。' }
    ]
  },
  7: { // Day7 问路方向
    topic: '问路方向',
    words: [
      { en: 'avenue', ph: '/ˈævənuː/', defs: [{ p: 'n.', c: '大道；林荫道' }], ex: 'The bank is on Fifth Avenue.', ec: '银行在第五大道上。' },
      { en: 'intersection', ph: '/ˌɪntərˈsekʃn/', defs: [{ p: 'n.', c: '十字路口；交叉路口' }], ex: 'The hotel is at the intersection.', ec: '酒店在十字路口。' },
      { en: 'downtown', ph: '/ˌdaʊnˈtaʊn/', defs: [{ p: 'n.', c: '市中心；商业区' }, { p: 'adv.', c: '往市中心' }], ex: 'We went downtown for shopping.', ec: '我们去市中心购物。' },
      { en: 'landmark', ph: '/ˈlændmɑːrk/', defs: [{ p: 'n.', c: '地标；标志性建筑' }], ex: 'The tower is a famous landmark.', ec: '这座塔是著名的地标。' },
      { en: 'block', ph: '/blɑːk/', defs: [{ p: 'n.', c: '街区；大楼' }], ex: 'The museum is two blocks away.', ec: '博物馆在两条街之外。' },
      { en: 'direction', ph: '/dəˈrekʃn/', defs: [{ p: 'n.', c: '方向；方位' }], ex: 'Which direction is the station?', ec: '车站在哪个方向？' },
      { en: 'straight', ph: '/streɪt/', defs: [{ p: 'adv.', c: '笔直地；直接' }], ex: 'Go straight and turn left.', ec: '直走然后左转。' },
      { en: 'corner', ph: '/ˈkɔːrnər/', defs: [{ p: 'n.', c: '拐角；角落' }], ex: 'The café is on the corner.', ec: '咖啡馆在拐角处。' },
      { en: 'opposite', ph: '/ˈɑːpəzɪt/', defs: [{ p: 'prep.', c: '在……对面' }, { p: 'adj.', c: '对面的' }], ex: 'The bank is opposite the mall.', ec: '银行在商场对面。' },
      { en: 'beside', ph: '/bɪˈsaɪd/', defs: [{ p: 'prep.', c: '在……旁边' }], ex: 'Sit beside me, please.', ec: '请坐在我旁边。' },
      { en: 'behind', ph: '/bɪˈhaɪnd/', defs: [{ p: 'prep.', c: '在……后面' }], ex: 'The school is behind the park.', ec: '学校在公园后面。' },
      { en: 'ahead', ph: '/əˈhed/', defs: [{ p: 'adv.', c: '在前面；向前' }], ex: 'The station is just ahead.', ec: '车站就在前面。' },
      { en: 'distance', ph: '/ˈdɪstəns/', defs: [{ p: 'n.', c: '距离；路程' }], ex: 'It is a short distance from here.', ec: '离这里很近。' },
      { en: 'nearby', ph: '/ˌnɪrˈbaɪ/', defs: [{ p: 'adj.', c: '附近的' }, { p: 'adv.', c: '在附近' }], ex: 'Is there a pharmacy nearby?', ec: '附近有药店吗？' },
      { en: 'turn', ph: '/tɜːrn/', defs: [{ p: 'v.', c: '转弯；转动' }, { p: 'n.', c: '转弯' }], ex: 'Turn right at the traffic light.', ec: '在红绿灯处右转。' },
      { en: 'map', ph: '/mæp/', defs: [{ p: 'n.', c: '地图' }], ex: 'She is looking at the map.', ec: '她正在看地图。' },
      { en: 'address', ph: '/əˈdres/', defs: [{ p: 'n.', c: '地址' }], ex: 'Please write down your address.', ec: '请写下你的地址。' },
      { en: 'sign', ph: '/saɪn/', defs: [{ p: 'n.', c: '标志；指示牌' }], ex: 'Follow the signs to the exit.', ec: '跟着指示牌走到出口。' },
      { en: 'left', ph: '/left/', defs: [{ p: 'n.', c: '左边' }, { p: 'adj.', c: '左边的' }], ex: 'The hotel is on your left.', ec: '酒店在你的左边。' },
      { en: 'right', ph: '/raɪt/', defs: [{ p: 'n.', c: '右边；权利' }, { p: 'adj.', c: '右边的' }], ex: 'Take the first right.', ec: '在第一个路口右转。' }
    ]
  },
  8: { // Day8 社交寒暄
    topic: '社交寒暄',
    words: [
      { en: 'conversation', ph: '/ˌkɑːnvərˈseɪʃn/', defs: [{ p: 'n.', c: '谈话；交谈' }], ex: 'We had a long conversation.', ec: '我们长谈了一次。' },
      { en: 'enjoyable', ph: '/ɪnˈdʒɔɪəbl/', defs: [{ p: 'adj.', c: '令人愉快的； enjoyable' }], ex: 'It was an enjoyable evening.', ec: '那是一个愉快的夜晚。' },
      { en: 'weather', ph: '/ˈweðər/', defs: [{ p: 'n.', c: '天气' }], ex: 'The weather is nice today.', ec: '今天天气很好。' },
      { en: 'weekend', ph: '/ˈwiːkend/', defs: [{ p: 'n.', c: '周末' }], ex: 'What are you doing this weekend?', ec: '这个周末你打算做什么？' },
      { en: 'plan', ph: '/plæn/', defs: [{ p: 'n.', c: '计划' }, { p: 'v.', c: '计划；打算' }], ex: 'Do you have any plans tonight?', ec: '你今晚有什么安排吗？' },
      { en: 'meeting', ph: '/ˈmiːtɪŋ/', defs: [{ p: 'n.', c: '会议；见面' }], ex: 'Nice meeting you all.', ec: '很高兴认识大家。' },
      { en: 'friend', ph: '/frend/', defs: [{ p: 'n.', c: '朋友' }], ex: 'She is my best friend.', ec: '她是我最好的朋友。' },
      { en: 'neighbor', ph: '/ˈneɪbər/', defs: [{ p: 'n.', c: '邻居' }], ex: 'Our neighbor is very kind.', ec: '我们的邻居非常友善。' },
      { en: 'visitor', ph: '/ˈvɪzɪtər/', defs: [{ p: 'n.', c: '访客；游客' }], ex: 'We have visitors from abroad.', ec: '我们有来自国外的访客。' },
      { en: 'together', ph: '/təˈɡeðər/', defs: [{ p: 'adv.', c: '一起；共同' }], ex: 'We had dinner together.', ec: '我们一起吃了晚饭。' },
      { en: 'perhaps', ph: '/pərˈhæps/', defs: [{ p: 'adv.', c: '也许；可能' }], ex: 'Perhaps we can meet again.', ec: '也许我们还能再见面。' },
      { en: 'invite', ph: '/ɪnˈvaɪt/', defs: [{ p: 'v.', c: '邀请' }], ex: 'They invited us to dinner.', ec: '他们邀请我们吃晚饭。' },
      { en: 'celebrate', ph: '/ˈselɪbreɪt/', defs: [{ p: 'v.', c: '庆祝' }], ex: 'Let us celebrate your birthday!', ec: '我们庆祝一下你的生日吧！' },
      { en: 'grateful', ph: '/ˈɡreɪtfl/', defs: [{ p: 'adj.', c: '感激的；感谢的' }], ex: 'I am grateful for your help.', ec: '我很感激你的帮助。' },
      { en: 'warm', ph: '/wɔːrm/', defs: [{ p: 'adj.', c: '温暖的；热情的' }], ex: 'They gave us a warm welcome.', ec: '他们热情地欢迎了我们。' },
      { en: 'friendly', ph: '/ˈfrendli/', defs: [{ p: 'adj.', c: '友好的；友善的' }], ex: 'People here are very friendly.', ec: '这里的人非常友好。' },
      { en: 'smile', ph: '/smaɪl/', defs: [{ p: 'n.', c: '微笑' }, { p: 'v.', c: '微笑' }], ex: 'She greeted me with a smile.', ec: '她微笑着和我打招呼。' },
      { en: 'laugh', ph: '/læf/', defs: [{ p: 'v.', c: '大笑' }, { p: 'n.', c: '笑声' }], ex: 'We laughed at his joke.', ec: '我们被他的笑话逗笑了。' },
      { en: 'joke', ph: '/dʒoʊk/', defs: [{ p: 'n.', c: '笑话；玩笑' }], ex: 'He told a funny joke.', ec: '他讲了个好笑的笑话。' },
      { en: 'topic', ph: '/ˈtɑːpɪk/', defs: [{ p: 'n.', c: '话题；主题' }], ex: 'Weather is a safe topic.', ec: '天气是个安全的话题。' }
    ]
  },
  9: { // Day9 医疗健康
    topic: '医疗健康',
    words: [
      { en: 'symptom', ph: '/ˈsɪmptəm/', defs: [{ p: 'n.', c: '症状' }], ex: 'Tell the doctor your symptoms.', ec: '把你的症状告诉医生。' },
      { en: 'prescription', ph: '/prɪˈskrɪpʃn/', defs: [{ p: 'n.', c: '处方；药方' }], ex: 'You need a prescription for this.', ec: '这个药需要处方。' },
      { en: 'allergy', ph: '/ˈælərdʒi/', defs: [{ p: 'n.', c: '过敏；过敏反应' }], ex: 'I have an allergy to peanuts.', ec: '我对花生过敏。' },
      { en: 'appointment', ph: '/əˈpɔɪntmənt/', defs: [{ p: 'n.', c: '预约；约会' }], ex: 'I have a doctor\'s appointment at three.', ec: '我三点约了医生。' },
      { en: 'fever', ph: '/ˈfiːvər/', defs: [{ p: 'n.', c: '发烧；发热' }], ex: 'He has a high fever.', ec: '他发高烧了。' },
      { en: 'cough', ph: '/kɔːf/', defs: [{ p: 'n.', c: '咳嗽' }, { p: 'v.', c: '咳嗽' }], ex: 'She has had a cough for a week.', ec: '她咳嗽了一个星期。' },
      { en: 'headache', ph: '/ˈhedeɪk/', defs: [{ p: 'n.', c: '头疼' }], ex: 'I have a terrible headache.', ec: '我头疼得厉害。' },
      { en: 'stomach', ph: '/ˈstʌmək/', defs: [{ p: 'n.', c: '胃；腹部' }], ex: 'My stomach hurts after lunch.', ec: '午饭后我的胃疼。' },
      { en: 'medicine', ph: '/ˈmedɪsn/', defs: [{ p: 'n.', c: '药；医学' }], ex: 'Take this medicine twice a day.', ec: '这个药一天吃两次。' },
      { en: 'tablet', ph: '/ˈtæblət/', defs: [{ p: 'n.', c: '药片；平板电脑' }], ex: 'Dissolve the tablet in water.', ec: '把药片溶于水中。' },
      { en: 'dose', ph: '/doʊs/', defs: [{ p: 'n.', c: '剂量；一剂' }], ex: 'Do not take more than one dose.', ec: '一次不要超过一剂。' },
      { en: 'patient', ph: '/ˈpeɪʃnt/', defs: [{ p: 'n.', c: '病人' }, { p: 'adj.', c: '有耐心的' }], ex: 'The waiting room is full of patients.', ec: '候诊室里满是病人。' },
      { en: 'doctor', ph: '/ˈdɑːktər/', defs: [{ p: 'n.', c: '医生；博士' }], ex: 'You should see a doctor.', ec: '你应该去看医生。' },
      { en: 'nurse', ph: '/nɜːrs/', defs: [{ p: 'n.', c: '护士' }], ex: 'The nurse took my temperature.', ec: '护士给我量了体温。' },
      { en: 'pharmacy', ph: '/ˈfɑːrməsi/', defs: [{ p: 'n.', c: '药房' }], ex: 'The pharmacy opens at nine.', ec: '药房九点开门。' },
      { en: 'clinic', ph: '/ˈklɪnɪk/', defs: [{ p: 'n.', c: '诊所；门诊部' }], ex: 'There is a clinic near the hotel.', ec: '酒店附近有一家诊所。' },
      { en: 'pain', ph: '/peɪn/', defs: [{ p: 'n.', c: '疼痛；痛苦' }], ex: 'I feel a sharp pain in my back.', ec: '我背部感到一阵剧痛。' },
      { en: 'hurt', ph: '/hɜːrt/', defs: [{ p: 'v.', c: '受伤；疼痛' }], ex: 'My knee hurts when I walk.', ec: '我走路时膝盖疼。' },
      { en: 'rest', ph: '/rest/', defs: [{ p: 'v.', c: '休息' }, { p: 'n.', c: '休息；剩余' }], ex: 'You need plenty of rest.', ec: '你需要好好休息。' },
      { en: 'healthy', ph: '/ˈhelθi/', defs: [{ p: 'adj.', c: '健康的' }], ex: 'Eating well keeps you healthy.', ec: '吃得好让你保持健康。' }
    ]
  },
  10: { // Day10 银行金钱
    topic: '银行金钱',
    words: [
      { en: 'currency', ph: '/ˈkɜːrənsi/', defs: [{ p: 'n.', c: '货币；通货' }], ex: 'What currency does Japan use?', ec: '日本用什么货币？' },
      { en: 'exchange', ph: '/ɪksˈtʃeɪndʒ/', defs: [{ p: 'v.', c: '兑换；交换' }], ex: 'I want to exchange yuan for dollars.', ec: '我想把人民币换成美元。' },
      { en: 'balance', ph: '/ˈbæləns/', defs: [{ p: 'n.', c: '余额；平衡' }], ex: 'My account balance is low.', ec: '我的账户余额不多了。' },
      { en: 'withdraw', ph: '/wɪðˈdrɔː/', defs: [{ p: 'v.', c: '取款；提取' }], ex: 'I need to withdraw some cash.', ec: '我需要取一些现金。' },
      { en: 'deposit', ph: '/dɪˈpɑːzɪt/', defs: [{ p: 'v.', c: '存款；存入' }, { p: 'n.', c: '押金' }], ex: 'She deposited the money in the bank.', ec: '她把钱存进了银行。' },
      { en: 'account', ph: '/əˈkaʊnt/', defs: [{ p: 'n.', c: '账户；账目' }], ex: 'I opened a savings account.', ec: '我开了一个储蓄账户。' },
      { en: 'cash', ph: '/kæʃ/', defs: [{ p: 'n.', c: '现金' }], ex: 'Do you accept cash?', ec: '你们收现金吗？' },
      { en: 'coin', ph: '/kɔɪn/', defs: [{ p: 'n.', c: '硬币' }], ex: 'I need some coins for the bus.', ec: '我需要一些硬币坐公交。' },
      { en: 'banknote', ph: '/ˈbæŋknoʊt/', defs: [{ p: 'n.', c: '纸币；钞票' }], ex: 'The banknote is very old.', ec: '这张钞票很旧。' },
      { en: 'interest', ph: '/ˈɪntrəst/', defs: [{ p: 'n.', c: '利息；兴趣' }], ex: 'The bank pays high interest.', ec: '这家银行利息很高。' },
      { en: 'loan', ph: '/loʊn/', defs: [{ p: 'n.', c: '贷款；借款' }], ex: 'They took out a loan for the house.', ec: '他们贷款买了房子。' },
      { en: 'credit', ph: '/ˈkredɪt/', defs: [{ p: 'n.', c: '信用；赊购' }], ex: 'I paid by credit card.', ec: '我用信用卡付的款。' },
      { en: 'password', ph: '/ˈpæswɜːrd/', defs: [{ p: 'n.', c: '密码；口令' }], ex: 'Never share your password.', ec: '永远不要分享你的密码。' },
      { en: 'receipt', ph: '/rɪˈsiːt/', defs: [{ p: 'n.', c: '收据；凭证' }], ex: 'Here is your receipt.', ec: '这是您的收据。' },
      { en: 'transaction', ph: '/trænˈzækʃn/', defs: [{ p: 'n.', c: '交易；业务' }], ex: 'The transaction went through.', ec: '交易成功了。' },
      { en: 'amount', ph: '/əˈmaʊnt/', defs: [{ p: 'n.', c: '金额；数量' }], ex: 'The amount is written below.', ec: '金额写在下面。' },
      { en: 'fee', ph: '/fiː/', defs: [{ p: 'n.', c: '费用；手续费' }], ex: 'There is a small service fee.', ec: '有一笔小额服务费。' },
      { en: 'change', ph: '/tʃeɪndʒ/', defs: [{ p: 'n.', c: '零钱；找零' }], ex: 'Here is your change, sir.', ec: '先生，这是找您的零钱。' },
      { en: 'savings', ph: '/ˈseɪvɪŋz/', defs: [{ p: 'n.', c: '储蓄；存款' }], ex: 'He spent all his savings.', ec: '他花光了所有积蓄。' },
      { en: 'budget', ph: '/ˈbʌdʒɪt/', defs: [{ p: 'n.', c: '预算' }], ex: 'We have a limited travel budget.', ec: '我们的旅行预算有限。' }
    ]
  }
};
