/**
 * js/data-vocab-c.js - 词汇积累 Day 21-30（200 词）
 * 每词：en 单词 / ph 美式音标 / defs 全部词性词义 / ex 例句 / ec 例句翻译
 */

const VOCAB_PART_C = {
  21: { // Day21 家庭与生活
    topic: '家庭与生活',
    words: [
      { en: 'relative', ph: '/ˈrelətɪv/', defs: [{ p: 'n.', c: '亲戚；亲属' }, { p: 'adj.', c: '相对的' }], ex: 'We visited our relatives during the holiday.', ec: '假期我们去拜访了亲戚。' },
      { en: 'generation', ph: '/ˌdʒenəˈreɪʃn/', defs: [{ p: 'n.', c: '一代人；辈分' }], ex: 'Three generations live in this house.', ec: '三代人住在这所房子里。' },
      { en: 'memory', ph: '/ˈmeməri/', defs: [{ p: 'n.', c: '记忆；回忆' }], ex: 'This photo brings back memories.', ec: '这张照片唤起了回忆。' },
      { en: 'traditional', ph: '/trəˈdɪʃənl/', defs: [{ p: 'adj.', c: '传统的；惯例的' }], ex: 'We had a traditional dinner.', ec: '我们吃了一顿传统晚餐。' },
      { en: 'celebration', ph: '/ˌselɪˈbreɪʃn/', defs: [{ p: 'n.', c: '庆祝；庆典' }], ex: 'The whole town joined the celebration.', ec: '全镇都参加了庆典。' },
      { en: 'wedding', ph: '/ˈwedɪŋ/', defs: [{ p: 'n.', c: '婚礼' }], ex: 'The wedding is in October.', ec: '婚礼在十月举行。' },
      { en: 'birthday', ph: '/ˈbɜːrθdeɪ/', defs: [{ p: 'n.', c: '生日' }], ex: 'Happy birthday to you!', ec: '祝你生日快乐！' },
      { en: 'gift', ph: '/ɡɪft/', defs: [{ p: 'n.', c: '礼物；赠品' }], ex: 'She gave me a lovely gift.', ec: '她送了我一件可爱的礼物。' },
      { en: 'family', ph: '/ˈfæməli/', defs: [{ p: 'n.', c: '家庭；家人' }], ex: 'My family is the most important thing.', ec: '家人对我来说最重要。' },
      { en: 'parent', ph: '/ˈperənt/', defs: [{ p: 'n.', c: '父母；家长' }], ex: 'My parents live in Shanghai.', ec: '我的父母住在上海。' },
      { en: 'child', ph: '/tʃaɪld/', defs: [{ p: 'n.', c: '孩子；儿童' }], ex: 'Every child needs love.', ec: '每个孩子都需要爱。' },
      { en: 'grandparent', ph: '/ˈɡrænperənt/', defs: [{ p: 'n.', c: '祖父母；外祖父母' }], ex: 'My grandparents tell great stories.', ec: '我的祖父母很会讲故事。' },
      { en: 'cousin', ph: '/ˈkʌzn/', defs: [{ p: 'n.', c: '堂（表）兄弟姐妹' }], ex: 'My cousin studies in Beijing.', ec: '我的表姐在北京上学。' },
      { en: 'uncle', ph: '/ˈʌŋkl/', defs: [{ p: 'n.', c: '叔叔；舅舅；伯父' }], ex: 'My uncle drives a taxi.', ec: '我叔叔开出租车。' },
      { en: 'aunt', ph: '/ænt/', defs: [{ p: 'n.', c: '阿姨；姑姑；舅妈' }], ex: 'My aunt makes great cakes.', ec: '我姑姑做的蛋糕很好吃。' },
      { en: 'nephew', ph: '/ˈnefjuː/', defs: [{ p: 'n.', c: '侄子；外甥' }], ex: 'My nephew is five years old.', ec: '我侄子五岁了。' },
      { en: 'niece', ph: '/niːs/', defs: [{ p: 'n.', c: '侄女；外甥女' }], ex: 'Her niece loves drawing.', ec: '她侄女喜欢画画。' },
      { en: 'marriage', ph: '/ˈmærɪdʒ/', defs: [{ p: 'n.', c: '婚姻；结婚' }], ex: 'They celebrated twenty years of marriage.', ec: '他们庆祝结婚二十周年。' },
      { en: 'ceremony', ph: '/ˈserəmoʊni/', defs: [{ p: 'n.', c: '仪式；典礼' }], ex: 'The opening ceremony starts at nine.', ec: '开幕式九点开始。' },
      { en: 'ancestor', ph: '/ˈænsestər/', defs: [{ p: 'n.', c: '祖先；祖宗' }], ex: 'We honor our ancestors in spring.', ec: '春天我们祭拜祖先。' }
    ]
  },
  22: { // Day22 爱好与娱乐
    topic: '爱好与娱乐',
    words: [
      { en: 'hobby', ph: '/ˈhɑːbi/', defs: [{ p: 'n.', c: '爱好；嗜好' }], ex: 'Gardening is my father\'s hobby.', ec: '园艺是我父亲的爱好。' },
      { en: 'instrument', ph: '/ˈɪnstrəmənt/', defs: [{ p: 'n.', c: '乐器；仪器' }], ex: 'She plays three instruments.', ec: '她会弹三种乐器。' },
      { en: 'performance', ph: '/pərˈfɔːrməns/', defs: [{ p: 'n.', c: '表演；演出；表现' }], ex: 'The performance was wonderful.', ec: '演出非常精彩。' },
      { en: 'relax', ph: '/rɪˈlæks/', defs: [{ p: 'v.', c: '放松；休息' }], ex: 'Listening to music helps me relax.', ec: '听音乐让我放松。' },
      { en: 'creative', ph: '/kriˈeɪtɪv/', defs: [{ p: 'adj.', c: '有创造力的；创意的' }], ex: 'She has a creative mind.', ec: '她很有创意。' },
      { en: 'painting', ph: '/ˈpeɪntɪŋ/', defs: [{ p: 'n.', c: '绘画；画作' }], ex: 'He spends weekends on painting.', ec: '他周末都在画画。' },
      { en: 'photography', ph: '/fəˈtɑːɡrəfi/', defs: [{ p: 'n.', c: '摄影；照相' }], ex: 'Photography is my new hobby.', ec: '摄影是我的新爱好。' },
      { en: 'dancing', ph: '/ˈdænsɪŋ/', defs: [{ p: 'n.', c: '跳舞；舞蹈' }], ex: 'She goes dancing every Friday.', ec: '她每周五去跳舞。' },
      { en: 'singing', ph: '/ˈsɪŋɪŋ/', defs: [{ p: 'n.', c: '唱歌' }], ex: 'Singing makes me happy.', ec: '唱歌让我开心。' },
      { en: 'reading', ph: '/ˈriːdɪŋ/', defs: [{ p: 'n.', c: '阅读' }], ex: 'Reading before bed is relaxing.', ec: '睡前阅读很放松。' },
      { en: 'movie', ph: '/ˈmuːvi/', defs: [{ p: 'n.', c: '电影' }], ex: 'We watched a movie last night.', ec: '我们昨晚看了一部电影。' },
      { en: 'concert', ph: '/ˈkɑːnsərt/', defs: [{ p: 'n.', c: '音乐会；演唱会' }], ex: 'The concert tickets sold out.', ec: '演唱会的票卖光了。' },
      { en: 'theater', ph: '/ˈθiːətər/', defs: [{ p: 'n.', c: '剧院；电影院' }], ex: 'The new theater opened downtown.', ec: '新剧院在市中心开业了。' },
      { en: 'music', ph: '/ˈmjuːzɪk/', defs: [{ p: 'n.', c: '音乐' }], ex: 'What kind of music do you like?', ec: '你喜欢什么类型的音乐？' },
      { en: 'art', ph: '/ɑːrt/', defs: [{ p: 'n.', c: '艺术；美术' }], ex: 'The city is famous for art.', ec: '这座城市以艺术闻名。' },
      { en: 'draw', ph: '/drɔː/', defs: [{ p: 'v.', c: '画画；绘制' }], ex: 'The kids like to draw animals.', ec: '孩子们喜欢画动物。' },
      { en: 'guitar', ph: '/ɡɪˈtɑːr/', defs: [{ p: 'n.', c: '吉他' }], ex: 'He plays the guitar well.', ec: '他吉他弹得很好。' },
      { en: 'piano', ph: '/piˈænoʊ/', defs: [{ p: 'n.', c: '钢琴' }], ex: 'She practices the piano daily.', ec: '她每天练钢琴。' },
      { en: 'chess', ph: '/tʃes/', defs: [{ p: 'n.', c: '国际象棋' }], ex: 'Grandpa and I play chess.', ec: '爷爷和我下棋。' },
      { en: 'camping', ph: '/ˈkæmpɪŋ/', defs: [{ p: 'n.', c: '露营；野营' }], ex: 'We went camping by the lake.', ec: '我们去湖边露营了。' }
    ]
  },
  23: { // Day23 通讯与网络
    topic: '通讯与网络',
    words: [
      { en: 'connect', ph: '/kəˈnekt/', defs: [{ p: 'v.', c: '连接；联系' }], ex: 'Connect your phone to the wifi.', ec: '把你的手机连上无线网。' },
      { en: 'message', ph: '/ˈmesɪdʒ/', defs: [{ p: 'n.', c: '消息；信息' }], ex: 'I left you a message.', ec: '我给你留了言。' },
      { en: 'signal', ph: '/ˈsɪɡnəl/', defs: [{ p: 'n.', c: '信号' }], ex: 'The signal is weak in the mountains.', ec: '山里信号很弱。' },
      { en: 'contact', ph: '/ˈkɑːntækt/', defs: [{ p: 'v.', c: '联系' }, { p: 'n.', c: '联系方式' }], ex: 'Contact me if you need help.', ec: '需要帮忙就联系我。' },
      { en: 'network', ph: '/ˈnetwɜːrk/', defs: [{ p: 'n.', c: '网络；人际网' }], ex: 'The network is down now.', ec: '网络现在断了。' },
      { en: 'internet', ph: '/ˈɪntərnet/', defs: [{ p: 'n.', c: '互联网' }], ex: 'You can book tickets on the internet.', ec: '你可以在网上订票。' },
      { en: 'email', ph: '/ˈiːmeɪl/', defs: [{ p: 'n.', c: '电子邮件' }, { p: 'v.', c: '发电子邮件' }], ex: 'I will email you the details.', ec: '我会把细节发邮件给你。' },
      { en: 'phone', ph: '/foʊn/', defs: [{ p: 'n.', c: '电话；手机' }], ex: 'My phone is out of battery.', ec: '我的手机没电了。' },
      { en: 'mobile', ph: '/ˈmoʊbl/', defs: [{ p: 'adj.', c: '移动的；手机的' }], ex: 'Please leave your mobile number.', ec: '请留下你的手机号。' },
      { en: 'screen', ph: '/skriːn/', defs: [{ p: 'n.', c: '屏幕' }], ex: 'The screen is cracked.', ec: '屏幕裂了。' },
      { en: 'keyboard', ph: '/ˈkiːbɔːrd/', defs: [{ p: 'n.', c: '键盘' }], ex: 'This keyboard is easy to type on.', ec: '这个键盘很好打字。' },
      { en: 'download', ph: '/ˌdaʊnˈloʊd/', defs: [{ p: 'v.', c: '下载' }], ex: 'Download the app for free.', ec: '免费下载这个应用。' },
      { en: 'upload', ph: '/ˌʌpˈloʊd/', defs: [{ p: 'v.', c: '上传' }], ex: 'Upload your photos here.', ec: '把你的照片上传到这里。' },
      { en: 'search', ph: '/sɜːrtʃ/', defs: [{ p: 'v.', c: '搜索；查找' }], ex: 'Search for the hotel online.', ec: '在网上搜一下这家酒店。' },
      { en: 'website', ph: '/ˈwebsaɪt/', defs: [{ p: 'n.', c: '网站' }], ex: 'The official website has the info.', ec: '官网有相关信息。' },
      { en: 'online', ph: '/ˌɑːnˈlaɪn/', defs: [{ p: 'adj.', c: '在线的；联网的' }], ex: 'I bought it online.', ec: '我在网上买的。' },
      { en: 'offline', ph: '/ˌɔːfˈlaɪn/', defs: [{ p: 'adj.', c: '离线的；断网的' }], ex: 'The map works offline.', ec: '这个地图离线也能用。' },
      { en: 'code', ph: '/koʊd/', defs: [{ p: 'n.', c: '代码；密码；验证码' }], ex: 'Enter the code from the message.', ec: '输入短信里的验证码。' },
      { en: 'data', ph: '/ˈdeɪtə/', defs: [{ p: 'n.', c: '数据；资料' }], ex: 'Save your data before you leave.', ec: '离开前保存好数据。' },
      { en: 'information', ph: '/ˌɪnfərˈmeɪʃn/', defs: [{ p: 'n.', c: '信息；资料' }], ex: 'Ask the desk for more information.', ec: '到前台了解更多信息。' }
    ]
  },
  24: { // Day24 紧急与安全
    topic: '紧急与安全',
    words: [
      { en: 'emergency', ph: '/ɪˈmɜːrdʒənsi/', defs: [{ p: 'n.', c: '紧急情况；突发事件' }], ex: 'Call this number in an emergency.', ec: '紧急情况拨打这个号码。' },
      { en: 'warn', ph: '/wɔːrn/', defs: [{ p: 'v.', c: '警告；提醒' }], ex: 'The sign warns of danger ahead.', ec: '标志警告前方有危险。' },
      { en: 'dangerous', ph: '/ˈdeɪndʒərəs/', defs: [{ p: 'adj.', c: '危险的' }], ex: 'It is dangerous to swim here.', ec: '在这里游泳很危险。' },
      { en: 'escape', ph: '/ɪˈskeɪp/', defs: [{ p: 'v.', c: '逃跑；逃离' }], ex: 'They escaped from the fire.', ec: '他们从火场逃了出来。' },
      { en: 'protect', ph: '/prəˈtekt/', defs: [{ p: 'v.', c: '保护；防护' }], ex: 'Wear a mask to protect yourself.', ec: '戴口罩保护自己。' },
      { en: 'safety', ph: '/ˈseɪfti/', defs: [{ p: 'n.', c: '安全；平安' }], ex: 'Your safety comes first.', ec: '你的安全最重要。' },
      { en: 'rescue', ph: '/ˈreskjuː/', defs: [{ p: 'v.', c: '营救；救援' }, { p: 'n.', c: '救援' }], ex: 'The team rescued the hikers.', ec: '救援队救出了徒步者。' },
      { en: 'fire', ph: '/ˈfaɪər/', defs: [{ p: 'n.', c: '火灾；火' }], ex: 'A fire broke out at midnight.', ec: '午夜发生了一场火灾。' },
      { en: 'flood', ph: '/flʌd/', defs: [{ p: 'n.', c: '洪水' }, { p: 'v.', c: '淹没' }], ex: 'The flood covered the fields.', ec: '洪水淹没了田地。' },
      { en: 'earthquake', ph: '/ˈɜːrθkweɪk/', defs: [{ p: 'n.', c: '地震' }], ex: 'The earthquake shook the whole city.', ec: '地震震动了整座城市。' },
      { en: 'thief', ph: '/θiːf/', defs: [{ p: 'n.', c: '小偷；贼' }], ex: 'The thief took her wallet.', ec: '小偷偷走了她的钱包。' },
      { en: 'robbery', ph: '/ˈrɑːbəri/', defs: [{ p: 'n.', c: '抢劫；盗窃' }], ex: 'The robbery happened at night.', ec: '抢劫发生在夜间。' },
      { en: 'police', ph: '/pəˈliːs/', defs: [{ p: 'n.', c: '警察；警方' }], ex: 'Call the police right away.', ec: '马上报警。' },
      { en: 'ambulance', ph: '/ˈæmbjələns/', defs: [{ p: 'n.', c: '救护车' }], ex: 'An ambulance arrived in minutes.', ec: '救护车几分钟就到了。' },
      { en: 'hospital', ph: '/ˈhɑːspɪtl/', defs: [{ p: 'n.', c: '医院' }], ex: 'The hospital is near the station.', ec: '医院在车站附近。' },
      { en: 'insurance', ph: '/ɪnˈʃʊrəns/', defs: [{ p: 'n.', c: '保险' }], ex: 'Travel insurance is recommended.', ec: '建议购买旅行保险。' },
      { en: 'alarm', ph: '/əˈlɑːrm/', defs: [{ p: 'n.', c: '警报；闹钟' }], ex: 'The fire alarm went off.', ec: '火警响了。' },
      { en: 'injury', ph: '/ˈɪndʒəri/', defs: [{ p: 'n.', c: '受伤；损伤' }], ex: 'He got an injury playing football.', ec: '他踢足球受了伤。' },
      { en: 'treatment', ph: '/ˈtriːtmənt/', defs: [{ p: 'n.', c: '治疗；处理' }], ex: 'The treatment takes two weeks.', ec: '治疗需要两周。' },
      { en: 'danger', ph: '/ˈdeɪndʒər/', defs: [{ p: 'n.', c: '危险' }], ex: 'The sign shows danger ahead.', ec: '标志显示前方危险。' }
    ]
  },
  25: { // Day25 外貌与衣着
    topic: '外貌与衣着',
    words: [
      { en: 'appearance', ph: '/əˈpɪrəns/', defs: [{ p: 'n.', c: '外貌；外表；出现' }], ex: 'Don\'t judge by appearance.', ec: '不要以貌取人。' },
      { en: 'elegant', ph: '/ˈelɪɡənt/', defs: [{ p: 'adj.', c: '优雅的；高雅的' }], ex: 'She wore an elegant dress.', ec: '她穿了一条优雅的裙子。' },
      { en: 'casual', ph: '/ˈkæʒuəl/', defs: [{ p: 'adj.', c: '休闲的；随意的' }], ex: 'The restaurant has a casual style.', ec: '这家餐厅风格休闲。' },
      { en: 'fit', ph: '/fɪt/', defs: [{ p: 'v.', c: '合身；适合' }, { p: 'adj.', c: '健康的' }], ex: 'The jacket fits you well.', ec: '这件夹克很适合你。' },
      { en: 'fashion', ph: '/ˈfæʃn/', defs: [{ p: 'n.', c: '时尚；潮流' }], ex: 'She follows the latest fashion.', ec: '她紧跟最新潮流。' },
      { en: 'style', ph: '/staɪl/', defs: [{ p: 'n.', c: '风格；款式' }], ex: 'I like your simple style.', ec: '我喜欢你简约的风格。' },
      { en: 'color', ph: '/ˈkʌlər/', defs: [{ p: 'n.', c: '颜色；色彩' }], ex: 'What color do you prefer?', ec: '你喜欢什么颜色？' },
      { en: 'pattern', ph: '/ˈpætərn/', defs: [{ p: 'n.', c: '图案；花纹' }], ex: 'The pattern is very traditional.', ec: '这个图案很传统。' },
      { en: 'fabric', ph: '/ˈfæbrɪk/', defs: [{ p: 'n.', c: '布料；织物' }], ex: 'This fabric feels soft.', ec: '这块布料摸起来很软。' },
      { en: 'cotton', ph: '/ˈkɑːtn/', defs: [{ p: 'n.', c: '棉；棉花' }], ex: 'Cotton shirts are cool in summer.', ec: '棉衬衫夏天穿很凉快。' },
      { en: 'wool', ph: '/wʊl/', defs: [{ p: 'n.', c: '羊毛；毛线' }], ex: 'This sweater is made of wool.', ec: '这件毛衣是羊毛的。' },
      { en: 'silk', ph: '/sɪlk/', defs: [{ p: 'n.', c: '丝绸' }], ex: 'The scarf is pure silk.', ec: '这条围巾是纯丝的。' },
      { en: 'leather', ph: '/ˈleðər/', defs: [{ p: 'n.', c: '皮革' }], ex: 'The bag is made of leather.', ec: '这个包是皮革做的。' },
      { en: 'shirt', ph: '/ʃɜːrt/', defs: [{ p: 'n.', c: '衬衫' }], ex: 'He ironed his white shirt.', ec: '他熨了自己的白衬衫。' },
      { en: 'dress', ph: '/dres/', defs: [{ p: 'n.', c: '连衣裙；裙子' }], ex: 'The blue dress suits her.', ec: '这条蓝裙子很适合她。' },
      { en: 'jacket', ph: '/ˈdʒækɪt/', defs: [{ p: 'n.', c: '夹克；短上衣' }], ex: 'Take a jacket; it is cold outside.', ec: '带件夹克，外面冷。' },
      { en: 'coat', ph: '/koʊt/', defs: [{ p: 'n.', c: '外套；大衣' }], ex: 'Hang your coat by the door.', ec: '把你的外套挂在门边。' },
      { en: 'shoes', ph: '/ʃuːz/', defs: [{ p: 'n.', c: '鞋子' }], ex: 'These shoes are very comfortable.', ec: '这双鞋非常舒服。' },
      { en: 'hat', ph: '/hæt/', defs: [{ p: 'n.', c: '帽子' }], ex: 'Wear a hat in the sun.', ec: '太阳下要戴帽子。' },
      { en: 'scarf', ph: '/skɑːrf/', defs: [{ p: 'n.', c: '围巾；头巾' }], ex: 'She knitted a scarf for me.', ec: '她给我织了一条围巾。' }
    ]
  },
  26: { // Day26 性格与品德
    topic: '性格与品德',
    words: [
      { en: 'generous', ph: '/ˈdʒenərəs/', defs: [{ p: 'adj.', c: '慷慨的；大方的' }], ex: 'He is generous with his time.', ec: '他在时间上很慷慨。' },
      { en: 'gentle', ph: '/ˈdʒentl/', defs: [{ p: 'adj.', c: '温和的；温柔的' }], ex: 'She has a gentle voice.', ec: '她声音很温柔。' },
      { en: 'humorous', ph: '/ˈhjuːmərəs/', defs: [{ p: 'adj.', c: '幽默的；风趣的' }], ex: 'His humorous stories made us laugh.', ec: '他幽默的故事逗笑了我们。' },
      { en: 'reliable', ph: '/rɪˈlaɪəbl/', defs: [{ p: 'adj.', c: '可靠的；可信赖的' }], ex: 'She is a reliable friend.', ec: '她是个可靠的朋友。' },
      { en: 'modest', ph: '/ˈmɑːdɪst/', defs: [{ p: 'adj.', c: '谦虚的；谦逊的' }], ex: 'He is modest about his success.', ec: '他对自己的成功很谦虚。' },
      { en: 'sincere', ph: '/sɪnˈsɪr/', defs: [{ p: 'adj.', c: '真诚的；诚挚的' }], ex: 'She gave me a sincere smile.', ec: '她给了我一个真诚的微笑。' },
      { en: 'careful', ph: '/ˈkerfl/', defs: [{ p: 'adj.', c: '小心的；仔细的' }], ex: 'Be careful with your luggage.', ec: '小心看管你的行李。' },
      { en: 'kind', ph: '/kaɪnd/', defs: [{ p: 'adj.', c: '善良的；友好的' }], ex: 'It is kind of you to help.', ec: '你真是太好了来帮忙。' },
      { en: 'smart', ph: '/smɑːrt/', defs: [{ p: 'adj.', c: '聪明的；机灵的' }], ex: 'She is smart and hardworking.', ec: '她又聪明又努力。' },
      { en: 'wise', ph: '/waɪz/', defs: [{ p: 'adj.', c: '明智的；睿智的' }], ex: 'That was a wise decision.', ec: '那是个明智的决定。' },
      { en: 'active', ph: '/ˈæktɪv/', defs: [{ p: 'adj.', c: '活跃的；积极的' }], ex: 'My grandpa is still very active.', ec: '我爷爷仍然很活跃。' },
      { en: 'quiet', ph: '/ˈkwaɪət/', defs: [{ p: 'adj.', c: '安静的；文静的' }], ex: 'He is quiet but thoughtful.', ec: '他话不多但很有想法。' },
      { en: 'shy', ph: '/ʃaɪ/', defs: [{ p: 'adj.', c: '害羞的；腼腆的' }], ex: 'She was shy at first.', ec: '她一开始很害羞。' },
      { en: 'outgoing', ph: '/ˈaʊtɡoʊɪŋ/', defs: [{ p: 'adj.', c: '外向的；开朗的' }], ex: 'He is outgoing and friendly.', ec: '他外向又友好。' },
      { en: 'positive', ph: '/ˈpɑːzətɪv/', defs: [{ p: 'adj.', c: '积极的；乐观的' }], ex: 'Keep a positive attitude.', ec: '保持积极的态度。' },
      { en: 'negative', ph: '/ˈneɡətɪv/', defs: [{ p: 'adj.', c: '消极的；负面的' }], ex: 'Try not to be so negative.', ec: '别这么消极。' },
      { en: 'independent', ph: '/ˌɪndɪˈpendənt/', defs: [{ p: 'adj.', c: '独立的；自主的' }], ex: 'She is an independent woman.', ec: '她是个独立的女性。' },
      { en: 'patient', ph: '/ˈpeɪʃnt/', defs: [{ p: 'adj.', c: '有耐心的' }], ex: 'A good teacher is patient.', ec: '好老师都有耐心。' },
      { en: 'honest', ph: '/ˈɑːnɪst/', defs: [{ p: 'adj.', c: '诚实的；正直的' }], ex: 'An honest answer is best.', ec: '诚实的回答最好。' },
      { en: 'friendly', ph: '/ˈfrendli/', defs: [{ p: 'adj.', c: '友好的' }], ex: 'The staff are friendly here.', ec: '这里的员工很友好。' }
    ]
  },
  27: { // Day27 环境与城市
    topic: '环境与城市',
    words: [
      { en: 'pollution', ph: '/pəˈluːʃn/', defs: [{ p: 'n.', c: '污染' }], ex: 'Air pollution is a big problem.', ec: '空气污染是个大问题。' },
      { en: 'recycle', ph: '/ˌriːˈsaɪkl/', defs: [{ p: 'v.', c: '回收利用；再循环' }], ex: 'Please recycle paper and plastic.', ec: '请回收纸和塑料。' },
      { en: 'neighborhood', ph: '/ˈneɪbərhʊd/', defs: [{ p: 'n.', c: '社区；街区' }], ex: 'We live in a quiet neighborhood.', ec: '我们住在一个安静的社区。' },
      { en: 'facility', ph: '/fəˈsɪləti/', defs: [{ p: 'n.', c: '设施；设备' }], ex: 'The hotel has good facilities.', ec: '这家酒店设施很好。' },
      { en: 'landscape', ph: '/ˈlændskeɪp/', defs: [{ p: 'n.', c: '风景；景观' }], ex: 'The landscape here is amazing.', ec: '这里的风景美极了。' },
      { en: 'environment', ph: '/ɪnˈvaɪrənmənt/', defs: [{ p: 'n.', c: '环境' }], ex: 'We should protect the environment.', ec: '我们应该保护环境。' },
      { en: 'nature', ph: '/ˈneɪtʃər/', defs: [{ p: 'n.', c: '自然；大自然' }], ex: 'They love being close to nature.', ec: '他们喜欢亲近自然。' },
      { en: 'energy', ph: '/ˈenərdʒi/', defs: [{ p: 'n.', c: '能源；精力' }], ex: 'Solar energy is clean.', ec: '太阳能很清洁。' },
      { en: 'waste', ph: '/weɪst/', defs: [{ p: 'n.', c: '垃圾；浪费' }, { p: 'v.', c: '浪费' }], ex: 'Don\'t waste food.', ec: '别浪费食物。' },
      { en: 'rubbish', ph: '/ˈrʌbɪʃ/', defs: [{ p: 'n.', c: '垃圾；废物（英式）' }], ex: 'Throw the rubbish in the bin.', ec: '把垃圾扔进垃圾桶。' },
      { en: 'clean', ph: '/kliːn/', defs: [{ p: 'adj.', c: '干净的' }, { p: 'v.', c: '打扫' }], ex: 'The streets are very clean.', ec: '街道非常干净。' },
      { en: 'dirty', ph: '/ˈdɜːrti/', defs: [{ p: 'adj.', c: '脏的；污秽的' }], ex: 'The water looks dirty.', ec: '水看起来很脏。' },
      { en: 'noisy', ph: '/ˈnɔɪzi/', defs: [{ p: 'adj.', c: '嘈杂的；吵闹的' }], ex: 'The bar is too noisy for us.', ec: '酒吧对我们来说太吵了。' },
      { en: 'crowded', ph: '/ˈkraʊdɪd/', defs: [{ p: 'adj.', c: '拥挤的；人多的' }], ex: 'The subway is crowded at eight.', ec: '八点地铁很挤。' },
      { en: 'peaceful', ph: '/ˈpiːsfl/', defs: [{ p: 'adj.', c: '宁静的；和平的' }], ex: 'The village is quiet and peaceful.', ec: '村子安静又宁静。' },
      { en: 'modern', ph: '/ˈmɑːdərn/', defs: [{ p: 'adj.', c: '现代的；时髦的' }], ex: 'The airport is very modern.', ec: '这个机场非常现代化。' },
      { en: 'historic', ph: '/hɪˈstɔːrɪk/', defs: [{ p: 'adj.', c: '历史悠久的；有历史意义的' }], ex: 'This is a historic building.', ec: '这是一座历史建筑。' },
      { en: 'village', ph: '/ˈvɪlɪdʒ/', defs: [{ p: 'n.', c: '村庄；乡村' }], ex: 'They stayed in a small village.', ec: '他们住在一个小村庄。' },
      { en: 'city', ph: '/ˈsɪti/', defs: [{ p: 'n.', c: '城市' }], ex: 'The city never sleeps.', ec: '这座城市从不睡觉。' },
      { en: 'suburb', ph: '/ˈsʌbɜːrb/', defs: [{ p: 'n.', c: '郊区；城郊' }], ex: 'They live in a quiet suburb.', ec: '他们住在安静的郊区。' }
    ]
  },
  28: { // Day28 服务与请求
    topic: '服务与请求',
    words: [
      { en: 'request', ph: '/rɪˈkwest/', defs: [{ p: 'n.', c: '请求；要求' }, { p: 'v.', c: '请求' }], ex: 'Your request has been sent.', ec: '你的请求已发送。' },
      { en: 'provide', ph: '/prəˈvaɪd/', defs: [{ p: 'v.', c: '提供；供应' }], ex: 'The hotel provides free breakfast.', ec: '酒店提供免费早餐。' },
      { en: 'confirm', ph: '/kənˈfɜːrm/', defs: [{ p: 'v.', c: '确认；证实' }], ex: 'Please confirm your booking.', ec: '请确认你的预订。' },
      { en: 'arrange', ph: '/əˈreɪndʒ/', defs: [{ p: 'v.', c: '安排；筹备' }], ex: 'Can you arrange a taxi for me?', ec: '能帮我安排一辆出租车吗？' },
      { en: 'service', ph: '/ˈsɜːrvɪs/', defs: [{ p: 'n.', c: '服务；服务项目' }], ex: 'The service here is excellent.', ec: '这里的服务非常好。' },
      { en: 'help', ph: '/help/', defs: [{ p: 'v.', c: '帮助' }, { p: 'n.', c: '帮助' }], ex: 'Could you help me with this?', ec: '你能帮我弄一下这个吗？' },
      { en: 'assist', ph: '/əˈsɪst/', defs: [{ p: 'v.', c: '协助；帮助' }], ex: 'A staff member will assist you.', ec: '会有工作人员协助你。' },
      { en: 'satisfy', ph: '/ˈsætɪsfaɪ/', defs: [{ p: 'v.', c: '使满意；满足' }], ex: 'We aim to satisfy every guest.', ec: '我们力求让每位客人满意。' },
      { en: 'appreciate', ph: '/əˈpriːʃieɪt/', defs: [{ p: 'v.', c: '感激；欣赏' }], ex: 'I appreciate your patience.', ec: '感谢你的耐心。' },
      { en: 'prefer', ph: '/prɪˈfɜːr/', defs: [{ p: 'v.', c: '更喜欢；宁愿' }], ex: 'I prefer tea to coffee.', ec: '比起咖啡我更喜欢茶。' },
      { en: 'choose', ph: '/tʃuːz/', defs: [{ p: 'v.', c: '选择；挑选' }], ex: 'You can choose any seat.', ec: '你可以选任意座位。' },
      { en: 'decide', ph: '/dɪˈsaɪd/', defs: [{ p: 'v.', c: '决定；下决心' }], ex: 'We decided to stay one more night.', ec: '我们决定再住一晚。' },
      { en: 'allow', ph: '/əˈlaʊ/', defs: [{ p: 'v.', c: '允许；准许' }], ex: 'Smoking is not allowed here.', ec: '这里禁止吸烟。' },
      { en: 'permit', ph: '/pərˈmɪt/', defs: [{ p: 'v.', c: '允许；许可' }, { p: 'n.', c: '许可证' }], ex: 'You need a permit to park here.', ec: '在这里停车需要许可证。' },
      { en: 'offer', ph: '/ˈɔːfər/', defs: [{ p: 'v.', c: '提供；提议' }, { p: 'n.', c: '报价；提议' }], ex: 'They offered us a better room.', ec: '他们给了我们一间更好的房间。' },
      { en: 'accept', ph: '/əkˈsept/', defs: [{ p: 'v.', c: '接受；同意' }], ex: 'Do you accept credit cards?', ec: '你们接受信用卡吗？' },
      { en: 'refuse', ph: '/rɪˈfjuːz/', defs: [{ p: 'v.', c: '拒绝；回绝' }], ex: 'He refused to answer.', ec: '他拒绝回答。' },
      { en: 'return', ph: '/rɪˈtɜːrn/', defs: [{ p: 'v.', c: '归还；返回' }], ex: 'Please return the key at checkout.', ec: '退房时请归还钥匙。' },
      { en: 'borrow', ph: '/ˈbɑːroʊ/', defs: [{ p: 'v.', c: '借入；借用' }], ex: 'May I borrow an umbrella?', ec: '我能借把伞吗？' },
      { en: 'lend', ph: '/lend/', defs: [{ p: 'v.', c: '借出；借给' }], ex: 'Could you lend me your phone?', ec: '能借我你的手机用一下吗？' }
    ]
  },
  29: { // Day29 观点与表达
    topic: '观点与表达',
    words: [
      { en: 'opinion', ph: '/əˈpɪnjən/', defs: [{ p: 'n.', c: '意见；看法' }], ex: 'Everyone has an opinion.', ec: '每个人都有看法。' },
      { en: 'suggest', ph: '/səˈdʒest/', defs: [{ p: 'v.', c: '建议；提议' }], ex: 'I suggest taking a taxi.', ec: '我建议打车。' },
      { en: 'suppose', ph: '/səˈpoʊz/', defs: [{ p: 'v.', c: '认为；猜想' }], ex: 'I suppose he is right.', ec: '我认为他是对的。' },
      { en: 'consider', ph: '/kənˈsɪdər/', defs: [{ p: 'v.', c: '考虑；认为' }], ex: 'We are considering renting a car.', ec: '我们在考虑租车。' },
      { en: 'agree', ph: '/əˈɡriː/', defs: [{ p: 'v.', c: '同意；赞成' }], ex: 'I agree with your plan.', ec: '我同意你的计划。' },
      { en: 'disagree', ph: '/ˌdɪsəˈɡriː/', defs: [{ p: 'v.', c: '不同意；有分歧' }], ex: 'I disagree with that idea.', ec: '我不同意那个想法。' },
      { en: 'believe', ph: '/bɪˈliːv/', defs: [{ p: 'v.', c: '相信；认为' }], ex: 'I believe you can do it.', ec: '我相信你能做到。' },
      { en: 'doubt', ph: '/daʊt/', defs: [{ p: 'v.', c: '怀疑；疑惑' }, { p: 'n.', c: '怀疑' }], ex: 'I doubt the train will be late.', ec: '我怀疑火车会晚点。' },
      { en: 'explain', ph: '/ɪkˈspleɪn/', defs: [{ p: 'v.', c: '解释；说明' }], ex: 'Could you explain this word?', ec: '你能解释一下这个单词吗？' },
      { en: 'express', ph: '/ɪkˈspres/', defs: [{ p: 'v.', c: '表达；表示' }], ex: 'She expressed her thanks warmly.', ec: '她热情地表达了感谢。' },
      { en: 'describe', ph: '/dɪˈskraɪb/', defs: [{ p: 'v.', c: '描述；形容' }], ex: 'Describe the man you saw.', ec: '描述一下你看到的那个人。' },
      { en: 'mention', ph: '/ˈmenʃn/', defs: [{ p: 'v.', c: '提到；说起' }], ex: 'He mentioned the meeting today.', ec: '他提到了今天的会议。' },
      { en: 'discuss', ph: '/dɪˈskʌs/', defs: [{ p: 'v.', c: '讨论；商量' }], ex: 'We discussed the plan over lunch.', ec: '我们午饭时讨论了计划。' },
      { en: 'convince', ph: '/kənˈvɪns/', defs: [{ p: 'v.', c: '说服；使相信' }], ex: 'She convinced me to join.', ec: '她说服我加入了。' },
      { en: 'conclusion', ph: '/kənˈkluːʒn/', defs: [{ p: 'n.', c: '结论；结束' }], ex: 'We came to a clear conclusion.', ec: '我们得出了明确的结论。' },
      { en: 'reason', ph: '/ˈriːzn/', defs: [{ p: 'n.', c: '原因；理由' }], ex: 'Tell me the reason for the delay.', ec: '告诉我延误的原因。' },
      { en: 'example', ph: '/ɪɡˈzæmpl/', defs: [{ p: 'n.', c: '例子；实例' }], ex: 'Give me an example, please.', ec: '请给我举个例子。' },
      { en: 'compare', ph: '/kəmˈper/', defs: [{ p: 'v.', c: '比较；对比' }], ex: 'Compare the prices before buying.', ec: '购买前比较一下价格。' },
      { en: 'decision', ph: '/dɪˈsɪʒn/', defs: [{ p: 'n.', c: '决定；抉择' }], ex: 'It was a hard decision.', ec: '这是个艰难的决定。' },
      { en: 'point', ph: '/pɔɪnt/', defs: [{ p: 'n.', c: '观点；要点' }], ex: 'That is a good point.', ec: '这是个好观点。' }
    ]
  },
  30: { // Day30 综合旅行高频词
    topic: '综合旅行高频词',
    words: [
      { en: 'passport', ph: '/ˈpæspɔːrt/', defs: [{ p: 'n.', c: '护照' }], ex: 'Keep your passport in a safe place.', ec: '把护照放在安全的地方。' },
      { en: 'visa', ph: '/ˈviːzə/', defs: [{ p: 'n.', c: '签证' }], ex: 'You need a visa to enter the country.', ec: '入境这个国家需要签证。' },
      { en: 'trip', ph: '/trɪp/', defs: [{ p: 'n.', c: '旅行；出行' }], ex: 'Have a safe trip home!', ec: '回家路上注意安全！' },
      { en: 'journey', ph: '/ˈdʒɜːrni/', defs: [{ p: 'n.', c: '旅程；行程' }], ex: 'The journey took six hours.', ec: '旅程花了六个小时。' },
      { en: 'destination', ph: '/ˌdestɪˈneɪʃn/', defs: [{ p: 'n.', c: '目的地；终点' }], ex: 'We reached our destination at noon.', ec: '我们中午到达了目的地。' },
      { en: 'book', ph: '/bʊk/', defs: [{ p: 'v.', c: '预订；预约' }, { p: 'n.', c: '书' }], ex: 'I booked a table for two.', ec: '我订了一张两人的桌子。' },
      { en: 'voucher', ph: '/ˈvaʊtʃər/', defs: [{ p: 'n.', c: '代金券；凭证' }], ex: 'Use this voucher for a discount.', ec: '用这张代金券可以打折。' },
      { en: 'tip', ph: '/tɪp/', defs: [{ p: 'n.', c: '小费；建议' }], ex: 'A ten percent tip is standard.', ec: '百分之十的小费是惯例。' },
      { en: 'cruise', ph: '/kruːz/', defs: [{ p: 'n.', c: '邮轮；乘船游览' }], ex: 'They took a cruise around the islands.', ec: '他们乘邮轮环游了群岛。' },
      { en: 'resort', ph: '/rɪˈzɔːrt/', defs: [{ p: 'n.', c: '度假村；旅游胜地' }], ex: 'The beach resort is lovely.', ec: '这个海滨度假村很漂亮。' },
      { en: 'guidebook', ph: '/ˈɡaɪdbʊk/', defs: [{ p: 'n.', c: '旅行指南；旅游手册' }], ex: 'The guidebook lists the best restaurants.', ec: '旅行指南列出了最好的餐厅。' },
      { en: 'companion', ph: '/kəmˈpænjən/', defs: [{ p: 'n.', c: '同伴；旅伴' }], ex: 'My sister was my travel companion.', ec: '我妹妹是我的旅行同伴。' },
      { en: 'suitcase', ph: '/ˈsuːtkeɪs/', defs: [{ p: 'n.', c: '手提箱；行李箱' }], ex: 'My suitcase is full of gifts.', ec: '我的行李箱装满了礼物。' },
      { en: 'snapshot', ph: '/ˈsnæpʃɑːt/', defs: [{ p: 'n.', c: '快照；照片' }], ex: 'Take a snapshot of the view.', ec: '拍一张风景快照。' },
      { en: 'board', ph: '/bɔːrd/', defs: [{ p: 'v.', c: '登机；上船' }, { p: 'n.', c: '板；告示牌' }], ex: 'Passengers may now board the plane.', ec: '乘客现在可以登机了。' },
      { en: 'check', ph: '/tʃek/', defs: [{ p: 'v.', c: '检查；核对' }, { p: 'n.', c: '检查；账单' }], ex: 'Check the schedule before you go.', ec: '出发前核对一下时刻表。' },
      { en: 'travel', ph: '/ˈtrævl/', defs: [{ p: 'v.', c: '旅行；游历' }, { p: 'n.', c: '旅行' }], ex: 'We love to travel abroad.', ec: '我们喜欢出国旅行。' },
      { en: 'sight', ph: '/saɪt/', defs: [{ p: 'n.', c: '风景；景象；景点' }], ex: 'The sunset was a beautiful sight.', ec: '日落是一道美丽的风景。' },
      { en: 'tourist', ph: '/ˈtʊrɪst/', defs: [{ p: 'n.', c: '游客；观光客' }], ex: 'The town is full of tourists in summer.', ec: '夏天小镇满是游客。' },
      { en: 'rate', ph: '/reɪt/', defs: [{ p: 'n.', c: '价格；费率；汇率' }], ex: 'The hotel rate includes breakfast.', ec: '酒店房价含早餐。' }
    ]
  }
};
