/**
 * js/data-vocab-b.js - 词汇积累 Day 11-20（200 词）
 * 每词：en 单词 / ph 美式音标 / defs 全部词性词义 / ex 例句 / ec 例句翻译
 */

const VOCAB_PART_B = {
  11: { // Day11 日常起居
    topic: '日常起居',
    words: [
      { en: 'schedule', ph: '/ˈskedʒuːl/', defs: [{ p: 'n.', c: '日程安排；时刻表' }], ex: 'My schedule is full today.', ec: '我今天日程排满了。' },
      { en: 'routine', ph: '/ruːˈtiːn/', defs: [{ p: 'n.', c: '日常；惯例' }, { p: 'adj.', c: '例行的' }], ex: 'Morning exercise is part of her routine.', ec: '晨练是她日常的一部分。' },
      { en: 'convenient', ph: '/kənˈviːniənt/', defs: [{ p: 'adj.', c: '方便的；便利的' }], ex: 'The subway is very convenient.', ec: '地铁非常方便。' },
      { en: 'comfortable', ph: '/ˈkʌmfərtəbl/', defs: [{ p: 'adj.', c: '舒适的；舒服的' }], ex: 'This bed is really comfortable.', ec: '这张床真的很舒服。' },
      { en: 'tidy', ph: '/ˈtaɪdi/', defs: [{ p: 'adj.', c: '整洁的；整齐的' }], ex: 'Please keep the room tidy.', ec: '请保持房间整洁。' },
      { en: 'household', ph: '/ˈhaʊshoʊld/', defs: [{ p: 'n.', c: '家庭；家务' }, { p: 'adj.', c: '家庭的' }], ex: 'They share the household chores.', ec: '他们分担家务。' },
      { en: 'cooking', ph: '/ˈkʊkɪŋ/', defs: [{ p: 'n.', c: '烹饪；做饭' }], ex: 'She is good at cooking.', ec: '她很擅长做饭。' },
      { en: 'cleaning', ph: '/ˈkliːnɪŋ/', defs: [{ p: 'n.', c: '打扫；清洁' }], ex: 'Cleaning takes an hour on Sundays.', ec: '周日打扫要花一个小时。' },
      { en: 'breakfast', ph: '/ˈbrekfəst/', defs: [{ p: 'n.', c: '早餐' }], ex: 'Breakfast is served at seven.', ec: '早餐七点供应。' },
      { en: 'lunch', ph: '/lʌntʃ/', defs: [{ p: 'n.', c: '午餐' }], ex: 'Let us have lunch together.', ec: '我们一起吃午饭吧。' },
      { en: 'dinner', ph: '/ˈdɪnər/', defs: [{ p: 'n.', c: '晚餐；正餐' }], ex: 'Dinner will be ready at six.', ec: '晚饭六点就好。' },
      { en: 'snack', ph: '/snæk/', defs: [{ p: 'n.', c: '零食；小吃' }], ex: 'I had a snack in the afternoon.', ec: '我下午吃了点零食。' },
      { en: 'kitchen', ph: '/ˈkɪtʃɪn/', defs: [{ p: 'n.', c: '厨房' }], ex: 'The kitchen smells great.', ec: '厨房里飘着香味。' },
      { en: 'bedroom', ph: '/ˈbedruːm/', defs: [{ p: 'n.', c: '卧室' }], ex: 'My bedroom faces the garden.', ec: '我的卧室朝向花园。' },
      { en: 'livingroom', ph: '/ˈlɪvɪŋ ruːm/', defs: [{ p: 'n.', c: '客厅' }], ex: 'We watch TV in the living room.', ec: '我们在客厅看电视。' },
      { en: 'balcony', ph: '/ˈbælkəni/', defs: [{ p: 'n.', c: '阳台' }], ex: 'Coffee on the balcony is lovely.', ec: '在阳台上喝咖啡很惬意。' },
      { en: 'garden', ph: '/ˈɡɑːrdn/', defs: [{ p: 'n.', c: '花园；菜园' }], ex: 'They grow vegetables in the garden.', ec: '他们在花园里种菜。' },
      { en: 'furniture', ph: '/ˈfɜːrnɪtʃər/', defs: [{ p: 'n.', c: '家具' }], ex: 'The new furniture is modern.', ec: '新家具很现代。' },
      { en: 'electric', ph: '/ɪˈlektrɪk/', defs: [{ p: 'adj.', c: '电的；电动的' }], ex: 'The kettle is electric.', ec: '这个水壶是电动的。' },
      { en: 'lock', ph: '/lɑːk/', defs: [{ p: 'v.', c: '锁上' }, { p: 'n.', c: '锁' }], ex: 'Remember to lock the door.', ec: '记得锁门。' }
    ]
  },
  12: { // Day12 天气与自然
    topic: '天气与自然',
    words: [
      { en: 'forecast', ph: '/ˈfɔːrkæst/', defs: [{ p: 'n.', c: '天气预报' }, { p: 'v.', c: '预测' }], ex: 'The forecast says rain tomorrow.', ec: '天气预报说明天有雨。' },
      { en: 'breeze', ph: '/briːz/', defs: [{ p: 'n.', c: '微风' }], ex: 'A cool breeze came from the sea.', ec: '海面吹来一阵凉风。' },
      { en: 'humidity', ph: '/hjuːˈmɪdəti/', defs: [{ p: 'n.', c: '湿度；潮湿' }], ex: 'The humidity is high in summer.', ec: '夏天湿度很高。' },
      { en: 'sunshine', ph: '/ˈsʌnʃaɪn/', defs: [{ p: 'n.', c: '阳光；日照' }], ex: 'We sat in the warm sunshine.', ec: '我们坐在温暖的阳光下。' },
      { en: 'temperature', ph: '/ˈtemprətʃər/', defs: [{ p: 'n.', c: '温度；气温' }], ex: 'The temperature dropped at night.', ec: '夜间气温下降了。' },
      { en: 'climate', ph: '/ˈklaɪmət/', defs: [{ p: 'n.', c: '气候' }], ex: 'The climate here is mild.', ec: '这里气候温和。' },
      { en: 'season', ph: '/ˈsiːzn/', defs: [{ p: 'n.', c: '季节' }], ex: 'Autumn is my favorite season.', ec: '秋天是我最喜欢的季节。' },
      { en: 'storm', ph: '/stɔːrm/', defs: [{ p: 'n.', c: '暴风雨' }], ex: 'The storm lasted all night.', ec: '暴风雨持续了一整夜。' },
      { en: 'rain', ph: '/reɪn/', defs: [{ p: 'n.', c: '雨' }, { p: 'v.', c: '下雨' }], ex: 'It rained heavily last night.', ec: '昨晚雨下得很大。' },
      { en: 'snow', ph: '/snoʊ/', defs: [{ p: 'n.', c: '雪' }, { p: 'v.', c: '下雪' }], ex: 'It snowed in the mountains.', ec: '山里下雪了。' },
      { en: 'wind', ph: '/wɪnd/', defs: [{ p: 'n.', c: '风' }], ex: 'The wind blew my hat away.', ec: '风把我的帽子吹跑了。' },
      { en: 'cloud', ph: '/klaʊd/', defs: [{ p: 'n.', c: '云' }], ex: 'Dark clouds are gathering.', ec: '乌云正在聚集。' },
      { en: 'sky', ph: '/skaɪ/', defs: [{ p: 'n.', c: '天空' }], ex: 'The sky is clear tonight.', ec: '今晚天空晴朗。' },
      { en: 'rainbow', ph: '/ˈreɪnboʊ/', defs: [{ p: 'n.', c: '彩虹' }], ex: 'A rainbow appeared after the rain.', ec: '雨后出现了一道彩虹。' },
      { en: 'sunny', ph: '/ˈsʌni/', defs: [{ p: 'adj.', c: '晴朗的；阳光充足的' }], ex: 'It is sunny and warm today.', ec: '今天晴朗又暖和。' },
      { en: 'cloudy', ph: '/ˈklaʊdi/', defs: [{ p: 'adj.', c: '多云的；阴天的' }], ex: 'The morning was cloudy.', ec: '早上是阴天。' },
      { en: 'rainy', ph: '/ˈreɪni/', defs: [{ p: 'adj.', c: '下雨的；多雨的' }], ex: 'We stayed in on the rainy day.', ec: '下雨天我们待在屋里。' },
      { en: 'windy', ph: '/ˈwɪndi/', defs: [{ p: 'adj.', c: '有风的' }], ex: 'It is too windy for a picnic.', ec: '风太大了，不适合野餐。' },
      { en: 'cold', ph: '/koʊld/', defs: [{ p: 'adj.', c: '寒冷的；冷淡的' }], ex: 'It gets cold in the evening.', ec: '晚上会变冷。' },
      { en: 'warm', ph: '/wɔːrm/', defs: [{ p: 'adj.', c: '温暖的；暖和的' }], ex: 'The weather is getting warmer.', ec: '天气在变暖。' }
    ]
  },
  13: { // Day13 时间与日期
    topic: '时间与日期',
    words: [
      { en: 'deadline', ph: '/ˈdedlaɪn/', defs: [{ p: 'n.', c: '截止日期；最后期限' }], ex: 'The deadline is next Friday.', ec: '截止日期是下周五。' },
      { en: 'punctual', ph: '/ˈpʌŋktʃuəl/', defs: [{ p: 'adj.', c: '守时的；准时的' }], ex: 'She is always punctual.', ec: '她总是很守时。' },
      { en: 'occasion', ph: '/əˈkeɪʒn/', defs: [{ p: 'n.', c: '场合；时机' }], ex: 'This dress is for special occasions.', ec: '这条裙子是特殊场合穿的。' },
      { en: 'available', ph: '/əˈveɪləbl/', defs: [{ p: 'adj.', c: '有空的；可获得的' }], ex: 'Are you available tomorrow?', ec: '你明天有空吗？' },
      { en: 'calendar', ph: '/ˈkælɪndər/', defs: [{ p: 'n.', c: '日历；日程表' }], ex: 'Mark the date on the calendar.', ec: '在日历上标出这个日期。' },
      { en: 'moment', ph: '/ˈmoʊmənt/', defs: [{ p: 'n.', c: '片刻；瞬间' }], ex: 'Wait a moment, please.', ec: '请稍等一下。' },
      { en: 'period', ph: '/ˈpɪriəd/', defs: [{ p: 'n.', c: '时期；一段时间' }], ex: 'We lived there for a short period.', ec: '我们在那里住过一小段时间。' },
      { en: 'century', ph: '/ˈsentʃəri/', defs: [{ p: 'n.', c: '世纪；百年' }], ex: 'The building dates back a century.', ec: '这座建筑有一个世纪的历史。' },
      { en: 'decade', ph: '/ˈdekeɪd/', defs: [{ p: 'n.', c: '十年' }], ex: 'The city changed over the decade.', ec: '这十年城市变化很大。' },
      { en: 'annual', ph: '/ˈænjuəl/', defs: [{ p: 'adj.', c: '每年的；年度的' }], ex: 'The annual meeting is in May.', ec: '年会在五月举行。' },
      { en: 'monthly', ph: '/ˈmʌnθli/', defs: [{ p: 'adj.', c: '每月的' }, { p: 'adv.', c: '每月一次' }], ex: 'The rent is paid monthly.', ec: '房租按月支付。' },
      { en: 'weekly', ph: '/ˈwiːkli/', defs: [{ p: 'adj.', c: '每周的' }, { p: 'adv.', c: '每周一次' }], ex: 'We have a weekly meeting.', ec: '我们每周开一次会。' },
      { en: 'duration', ph: '/duˈreɪʃn/', defs: [{ p: 'n.', c: '持续时间；期间' }], ex: 'The duration of the tour is two hours.', ec: '这次游览持续两个小时。' },
      { en: 'early', ph: '/ˈɜːrli/', defs: [{ p: 'adj.', c: '早的' }, { p: 'adv.', c: '早；提前' }], ex: 'We arrived early for the show.', ec: '我们提前到了演出现场。' },
      { en: 'late', ph: '/leɪt/', defs: [{ p: 'adj.', c: '迟的；晚的' }, { p: 'adv.', c: '迟到' }], ex: 'Sorry, I am running late.', ec: '抱歉，我要迟到了。' },
      { en: 'soon', ph: '/suːn/', defs: [{ p: 'adv.', c: '很快；不久' }], ex: 'The bus will arrive soon.', ec: '公交车很快就到。' },
      { en: 'later', ph: '/ˈleɪtər/', defs: [{ p: 'adv.', c: '稍后；以后' }], ex: 'I will call you later.', ec: '我稍后给你打电话。' },
      { en: 'finally', ph: '/ˈfaɪnəli/', defs: [{ p: 'adv.', c: '最终；终于' }], ex: 'The train finally arrived.', ec: '火车终于到了。' },
      { en: 'immediately', ph: '/ɪˈmiːdiətli/', defs: [{ p: 'adv.', c: '立即；马上' }], ex: 'Please come immediately.', ec: '请马上过来。' },
      { en: 'recently', ph: '/ˈriːsntli/', defs: [{ p: 'adv.', c: '最近；近来' }], ex: 'Have you seen her recently?', ec: '你最近见过她吗？' }
    ]
  },
  14: { // Day14 情绪与感受
    topic: '情绪与感受',
    words: [
      { en: 'nervous', ph: '/ˈnɜːrvəs/', defs: [{ p: 'adj.', c: '紧张的；焦虑的' }], ex: 'I felt nervous before the speech.', ec: '演讲前我很紧张。' },
      { en: 'confident', ph: '/ˈkɑːnfɪdənt/', defs: [{ p: 'adj.', c: '自信的；有把握的' }], ex: 'She is confident about the test.', ec: '她对考试很有把握。' },
      { en: 'relieved', ph: '/rɪˈliːvd/', defs: [{ p: 'adj.', c: '如释重负的；宽慰的' }], ex: 'I was relieved to hear the news.', ec: '听到这个消息我松了口气。' },
      { en: 'frustrated', ph: '/ˈfrʌstreɪtɪd/', defs: [{ p: 'adj.', c: '沮丧的；懊恼的' }], ex: 'He felt frustrated with the delay.', ec: '延误让他很懊恼。' },
      { en: 'grateful', ph: '/ˈɡreɪtfl/', defs: [{ p: 'adj.', c: '感激的；感谢的' }], ex: 'I am grateful for your kindness.', ec: '我很感激你的好意。' },
      { en: 'excited', ph: '/ɪkˈsaɪtɪd/', defs: [{ p: 'adj.', c: '兴奋的；激动的' }], ex: 'The kids are excited about the trip.', ec: '孩子们对这次旅行很兴奋。' },
      { en: 'worried', ph: '/ˈwɜːrid/', defs: [{ p: 'adj.', c: '担心的；忧虑的' }], ex: 'Do not be worried about it.', ec: '别为这事担心。' },
      { en: 'surprised', ph: '/sərˈpraɪzd/', defs: [{ p: 'adj.', c: '惊讶的；吃惊的' }], ex: 'I was surprised by the gift.', ec: '这个礼物让我很惊喜。' },
      { en: 'proud', ph: '/praʊd/', defs: [{ p: 'adj.', c: '自豪的；骄傲的' }], ex: 'We are proud of you.', ec: '我们为你感到骄傲。' },
      { en: 'lonely', ph: '/ˈloʊnli/', defs: [{ p: 'adj.', c: '孤独的；寂寞的' }], ex: 'She felt lonely in the new city.', ec: '在新城市里她感到孤独。' },
      { en: 'satisfied', ph: '/ˈsætɪsfaɪd/', defs: [{ p: 'adj.', c: '满意的；满足的' }], ex: 'He is satisfied with the result.', ec: '他对结果很满意。' },
      { en: 'disappointed', ph: '/ˌdɪsəˈpɔɪntɪd/', defs: [{ p: 'adj.', c: '失望的；沮丧的' }], ex: 'We were disappointed by the show.', ec: '演出让我们很失望。' },
      { en: 'curious', ph: '/ˈkjʊriəs/', defs: [{ p: 'adj.', c: '好奇的；求知欲强的' }], ex: 'The child is curious about everything.', ec: '这孩子对什么都好奇。' },
      { en: 'patient', ph: '/ˈpeɪʃnt/', defs: [{ p: 'adj.', c: '有耐心的' }], ex: 'Be patient with beginners.', ec: '对初学者要有耐心。' },
      { en: 'calm', ph: '/kɑːm/', defs: [{ p: 'adj.', c: '平静的；镇定的' }], ex: 'Stay calm and call for help.', ec: '保持冷静并呼救。' },
      { en: 'happy', ph: '/ˈhæpi/', defs: [{ p: 'adj.', c: '快乐的；幸福的' }], ex: 'The news made everyone happy.', ec: '这个消息让每个人都很开心。' },
      { en: 'sad', ph: '/sæd/', defs: [{ p: 'adj.', c: '悲伤的；难过的' }], ex: 'She felt sad saying goodbye.', ec: '告别时她很难过。' },
      { en: 'angry', ph: '/ˈæŋɡri/', defs: [{ p: 'adj.', c: '生气的；愤怒的' }], ex: 'He was angry about the mistake.', ec: '他对这个错误很生气。' },
      { en: 'afraid', ph: '/əˈfreɪd/', defs: [{ p: 'adj.', c: '害怕的；担心的' }], ex: 'I am afraid of flying.', ec: '我害怕坐飞机。' },
      { en: 'brave', ph: '/breɪv/', defs: [{ p: 'adj.', c: '勇敢的' }], ex: 'It was brave of you to speak up.', ec: '你能开口说是很勇敢的。' }
    ]
  },
  15: { // Day15 餐饮进阶
    topic: '餐饮进阶',
    words: [
      { en: 'ingredient', ph: '/ɪnˈɡriːdiənt/', defs: [{ p: 'n.', c: '食材；原料' }], ex: 'The dish has five ingredients.', ec: '这道菜有五种食材。' },
      { en: 'flavor', ph: '/ˈfleɪvər/', defs: [{ p: 'n.', c: '味道；风味' }], ex: 'This tea has a fruity flavor.', ec: '这种茶有果味。' },
      { en: 'vegetarian', ph: '/ˌvedʒəˈteriən/', defs: [{ p: 'n.', c: '素食者' }, { p: 'adj.', c: '素食的' }], ex: 'The restaurant has a vegetarian menu.', ec: '这家餐厅有素食菜单。' },
      { en: 'gourmet', ph: '/ˈɡʊrmeɪ/', defs: [{ p: 'n.', c: '美食家' }, { p: 'adj.', c: '美食的' }], ex: 'He is a real gourmet.', ec: '他是个真正的美食家。' },
      { en: 'portion', ph: '/ˈpɔːrʃn/', defs: [{ p: 'n.', c: '份量；一份' }], ex: 'The portions here are large.', ec: '这里的份量很大。' },
      { en: 'recipe', ph: '/ˈresəpi/', defs: [{ p: 'n.', c: '食谱；配方' }], ex: 'This is my grandmother\'s recipe.', ec: '这是我祖母的食谱。' },
      { en: 'nutrition', ph: '/nuˈtrɪʃn/', defs: [{ p: 'n.', c: '营养' }], ex: 'Fruits are full of nutrition.', ec: '水果富含营养。' },
      { en: 'protein', ph: '/ˈproʊtiːn/', defs: [{ p: 'n.', c: '蛋白质' }], ex: 'Eggs are rich in protein.', ec: '鸡蛋富含蛋白质。' },
      { en: 'vitamin', ph: '/ˈvaɪtəmɪn/', defs: [{ p: 'n.', c: '维生素' }], ex: 'Oranges contain vitamin C.', ec: '橙子含有维生素 C。' },
      { en: 'carbohydrate', ph: '/ˌkɑːrboʊˈhaɪdreɪt/', defs: [{ p: 'n.', c: '碳水化合物' }], ex: 'Rice is a carbohydrate.', ec: '米饭是碳水化合物。' },
      { en: 'seasoning', ph: '/ˈsiːznɪŋ/', defs: [{ p: 'n.', c: '调味品；佐料' }], ex: 'Add less seasoning for the child.', ec: '给孩子少放点调料。' },
      { en: 'pepper', ph: '/ˈpepər/', defs: [{ p: 'n.', c: '胡椒；辣椒' }], ex: 'Could I have some salt and pepper?', ec: '能给我一些盐和胡椒吗？' },
      { en: 'salt', ph: '/sɔːlt/', defs: [{ p: 'n.', c: '盐' }], ex: 'The soup needs more salt.', ec: '汤里需要多加点盐。' },
      { en: 'sugar', ph: '/ˈʃʊɡər/', defs: [{ p: 'n.', c: '糖' }], ex: 'I take my coffee without sugar.', ec: '我喝咖啡不加糖。' },
      { en: 'oil', ph: '/ɔɪl/', defs: [{ p: 'n.', c: '油；食用油' }], ex: 'The dish is cooked in olive oil.', ec: '这道菜用橄榄油烹制。' },
      { en: 'vinegar', ph: '/ˈvɪnɪɡər/', defs: [{ p: 'n.', c: '醋' }], ex: 'The salad is dressed with vinegar.', ec: '沙拉用醋调味。' },
      { en: 'bakery', ph: '/ˈbeɪkəri/', defs: [{ p: 'n.', c: '面包店；烘焙坊' }], ex: 'The bakery opens at six.', ec: '面包店六点开门。' },
      { en: 'café', ph: '/kæˈfeɪ/', defs: [{ p: 'n.', c: '咖啡馆；小餐馆' }], ex: 'We met at a small café.', ec: '我们在一家小咖啡馆见面。' },
      { en: 'restaurant', ph: '/ˈrestərɑːnt/', defs: [{ p: 'n.', c: '餐厅；餐馆' }], ex: 'That restaurant is always full.', ec: '那家餐厅总是满座。' },
      { en: 'buffet', ph: '/bəˈfeɪ/', defs: [{ p: 'n.', c: '自助餐' }], ex: 'The hotel offers a breakfast buffet.', ec: '酒店提供自助早餐。' }
    ]
  },
  16: { // Day16 旅行观光
    topic: '旅行观光',
    words: [
      { en: 'attraction', ph: '/əˈtrækʃn/', defs: [{ p: 'n.', c: '景点；吸引力' }], ex: 'The tower is the top attraction.', ec: '这座塔是最热门的景点。' },
      { en: 'itinerary', ph: '/aɪˈtɪnəreri/', defs: [{ p: 'n.', c: '行程；旅行计划' }], ex: 'Our itinerary includes three cities.', ec: '我们的行程包括三个城市。' },
      { en: 'souvenir', ph: '/ˌsuːvəˈnɪr/', defs: [{ p: 'n.', c: '纪念品' }], ex: 'I bought a souvenir for my mom.', ec: '我给妈妈买了个纪念品。' },
      { en: 'memorable', ph: '/ˈmemərəbl/', defs: [{ p: 'adj.', c: '难忘的；值得纪念的' }], ex: 'It was a memorable trip.', ec: '那是一次难忘的旅行。' },
      { en: 'explore', ph: '/ɪkˈsplɔːr/', defs: [{ p: 'v.', c: '探索；考察' }], ex: 'We explored the old town on foot.', ec: '我们步行探索了老城。' },
      { en: 'sightseeing', ph: '/ˈsaɪtsiːɪŋ/', defs: [{ p: 'n.', c: '观光；游览' }], ex: 'We went sightseeing in the city.', ec: '我们到城里观光。' },
      { en: 'guide', ph: '/ɡaɪd/', defs: [{ p: 'n.', c: '导游；向导' }, { p: 'v.', c: '带领' }], ex: 'The guide showed us around.', ec: '导游带我们参观。' },
      { en: 'tour', ph: '/tʊr/', defs: [{ p: 'n.', c: '旅行团；游览' }], ex: 'We joined a day tour.', ec: '我们参加了一个一日游。' },
      { en: 'museum', ph: '/mjuˈziːəm/', defs: [{ p: 'n.', c: '博物馆' }], ex: 'The museum is closed on Mondays.', ec: '博物馆周一闭馆。' },
      { en: 'gallery', ph: '/ˈɡæləri/', defs: [{ p: 'n.', c: '画廊；美术馆' }], ex: 'The gallery displays local art.', ec: '美术馆展出当地艺术。' },
      { en: 'castle', ph: '/ˈkæsl/', defs: [{ p: 'n.', c: '城堡' }], ex: 'The castle sits on a hill.', ec: '城堡坐落在山上。' },
      { en: 'temple', ph: '/ˈtempl/', defs: [{ p: 'n.', c: '寺庙；神殿' }], ex: 'We visited an ancient temple.', ec: '我们参观了一座古庙。' },
      { en: 'beach', ph: '/biːtʃ/', defs: [{ p: 'n.', c: '海滩' }], ex: 'The beach is crowded in July.', ec: '七月海滩人很多。' },
      { en: 'mountain', ph: '/ˈmaʊntn/', defs: [{ p: 'n.', c: '山；山脉' }], ex: 'We hiked up the mountain.', ec: '我们徒步上了山。' },
      { en: 'lake', ph: '/leɪk/', defs: [{ p: 'n.', c: '湖' }], ex: 'The lake is clear and blue.', ec: '湖水清澈湛蓝。' },
      { en: 'river', ph: '/ˈrɪvər/', defs: [{ p: 'n.', c: '河流' }], ex: 'A river runs through the city.', ec: '一条河穿城而过。' },
      { en: 'island', ph: '/ˈaɪlənd/', defs: [{ p: 'n.', c: '岛屿' }], ex: 'We took a boat to the island.', ec: '我们坐船去了岛上。' },
      { en: 'bridge', ph: '/brɪdʒ/', defs: [{ p: 'n.', c: '桥' }], ex: 'The bridge lights up at night.', ec: '这座桥晚上会亮灯。' },
      { en: 'fountain', ph: '/ˈfaʊntn/', defs: [{ p: 'n.', c: '喷泉' }], ex: 'Kids play near the fountain.', ec: '孩子们在喷泉旁玩耍。' },
      { en: 'monument', ph: '/ˈmɑːnjumənt/', defs: [{ p: 'n.', c: '纪念碑；历史遗迹' }], ex: 'The monument honors the soldiers.', ec: '这座纪念碑纪念士兵。' }
    ]
  },
  17: { // Day17 交通进阶
    topic: '交通进阶',
    words: [
      { en: 'highway', ph: '/ˈhaɪweɪ/', defs: [{ p: 'n.', c: '高速公路' }], ex: 'The highway connects the two cities.', ec: '这条高速连接两座城市。' },
      { en: 'commute', ph: '/kəˈmjuːt/', defs: [{ p: 'v.', c: '通勤；上下班往返' }, { p: 'n.', c: '通勤' }], ex: 'She commutes by train daily.', ec: '她每天坐火车通勤。' },
      { en: 'traffic', ph: '/ˈtræfɪk/', defs: [{ p: 'n.', c: '交通；车流' }], ex: 'The traffic is heavy at rush hour.', ec: '高峰时段交通很拥堵。' },
      { en: 'driver', ph: '/ˈdraɪvər/', defs: [{ p: 'n.', c: '司机；驾驶员' }], ex: 'The driver knows the city well.', ec: '司机对这座城市很熟。' },
      { en: 'helmet', ph: '/ˈhelmɪt/', defs: [{ p: 'n.', c: '头盔' }], ex: 'Wear a helmet when riding.', ec: '骑车时要戴头盔。' },
      { en: 'accident', ph: '/ˈæksɪdənt/', defs: [{ p: 'n.', c: '事故；意外' }], ex: 'There was an accident on the road.', ec: '路上发生了一起事故。' },
      { en: 'speed', ph: '/spiːd/', defs: [{ p: 'n.', c: '速度' }, { p: 'v.', c: '加速' }], ex: 'The train reached full speed.', ec: '火车达到了全速。' },
      { en: 'brake', ph: '/breɪk/', defs: [{ p: 'n.', c: '刹车' }, { p: 'v.', c: '刹车' }], ex: 'He braked suddenly at the light.', ec: '他在红绿灯前突然刹车。' },
      { en: 'signal', ph: '/ˈsɪɡnəl/', defs: [{ p: 'n.', c: '信号灯；信号' }], ex: 'Wait for the green signal.', ec: '等绿灯亮。' },
      { en: 'parking', ph: '/ˈpɑːrkɪŋ/', defs: [{ p: 'n.', c: '停车；停车场' }], ex: 'Parking is free after six.', ec: '六点后停车免费。' },
      { en: 'garage', ph: '/ɡəˈrɑːʒ/', defs: [{ p: 'n.', c: '车库；修车厂' }], ex: 'The car is in the garage.', ec: '车在车库里。' },
      { en: 'petrol', ph: '/ˈpetrəl/', defs: [{ p: 'n.', c: '汽油（英式）' }], ex: 'We need to fill up with petrol.', ec: '我们需要加满汽油。' },
      { en: 'diesel', ph: '/ˈdiːzl/', defs: [{ p: 'n.', c: '柴油' }], ex: 'This truck runs on diesel.', ec: '这辆卡车烧柴油。' },
      { en: 'electric', ph: '/ɪˈlektrɪk/', defs: [{ p: 'adj.', c: '电动的' }], ex: 'Electric cars are getting popular.', ec: '电动车越来越受欢迎。' },
      { en: 'tunnel', ph: '/ˈtʌnl/', defs: [{ p: 'n.', c: '隧道；地道' }], ex: 'The train went through a tunnel.', ec: '火车穿过一条隧道。' },
      { en: 'roundabout', ph: '/ˈraʊndəbaʊt/', defs: [{ p: 'n.', c: '环岛；环形交叉路口' }], ex: 'Take the second exit at the roundabout.', ec: '在环岛第二个出口出。' },
      { en: 'pavement', ph: '/ˈpeɪvmənt/', defs: [{ p: 'n.', c: '人行道' }], ex: 'Walk on the pavement, please.', ec: '请在人行道上走。' },
      { en: 'zebra', ph: '/ˈziːbrə/', defs: [{ p: 'n.', c: '斑马线' }], ex: 'Cross the street at the zebra crossing.', ec: '在斑马线处过马路。' },
      { en: 'junction', ph: '/ˈdʒʌŋkʃn/', defs: [{ p: 'n.', c: '交叉路口；枢纽' }], ex: 'The store is near the junction.', ec: '商店在交叉路口附近。' },
      { en: 'ride', ph: '/raɪd/', defs: [{ p: 'v.', c: '骑；乘坐' }, { p: 'n.', c: '乘坐；搭车' }], ex: 'Can I ride the bus to town?', ec: '我能坐公交进城吗？' }
    ]
  },
  18: { // Day18 购物进阶
    topic: '购物进阶',
    words: [
      { en: 'label', ph: '/ˈleɪbl/', defs: [{ p: 'n.', c: '标签；商标' }], ex: 'Check the label for the size.', ec: '看标签上的尺码。' },
      { en: 'luxury', ph: '/ˈlʌkʃəri/', defs: [{ p: 'n.', c: '奢侈品；奢华' }, { p: 'adj.', c: '奢华的' }], ex: 'The hotel is a luxury one.', ec: '这是一家豪华酒店。' },
      { en: 'affordable', ph: '/əˈfɔːrdəbl/', defs: [{ p: 'adj.', c: '负担得起的；价格合理的' }], ex: 'The prices here are affordable.', ec: '这里的价格很实惠。' },
      { en: 'warranty', ph: '/ˈwɔːrənti/', defs: [{ p: 'n.', c: '保修；质保' }], ex: 'The phone has a two-year warranty.', ec: '这部手机保修两年。' },
      { en: 'invoice', ph: '/ˈɪnvɔɪs/', defs: [{ p: 'n.', c: '发票；发货单' }], ex: 'Ask for an invoice when you pay.', ec: '付款时要发票。' },
      { en: 'deliver', ph: '/dɪˈlɪvər/', defs: [{ p: 'v.', c: '送货；递送' }], ex: 'They deliver within three days.', ec: '他们三天内送货。' },
      { en: 'courier', ph: '/ˈkʊriər/', defs: [{ p: 'n.', c: '快递员；信使' }], ex: 'The courier will call before delivery.', ec: '快递员送货前会打电话。' },
      { en: 'package', ph: '/ˈpækɪdʒ/', defs: [{ p: 'n.', c: '包裹；包装' }], ex: 'A package arrived for you.', ec: '有你的一个包裹到了。' },
      { en: 'parcel', ph: '/ˈpɑːrsl/', defs: [{ p: 'n.', c: '包裹；小包' }], ex: 'She sent a parcel home.', ec: '她寄了一个包裹回家。' },
      { en: 'stock', ph: '/stɑːk/', defs: [{ p: 'n.', c: '库存；现货' }, { p: 'v.', c: '备货' }], ex: 'Sorry, that item is out of stock.', ec: '抱歉，那件商品缺货。' },
      { en: 'available', ph: '/əˈveɪləbl/', defs: [{ p: 'adj.', c: '有货的；可得到的' }], ex: 'This size is still available.', ec: '这个尺码还有货。' },
      { en: 'popular', ph: '/ˈpɑːpjələr/', defs: [{ p: 'adj.', c: '受欢迎的；流行的' }], ex: 'It is a popular gift choice.', ec: '这是很受欢迎的礼物选择。' },
      { en: 'trendy', ph: '/ˈtrendi/', defs: [{ p: 'adj.', c: '时髦的；新潮的' }], ex: 'She wears trendy clothes.', ec: '她穿得很时髦。' },
      { en: 'classic', ph: '/ˈklæsɪk/', defs: [{ p: 'adj.', c: '经典的；古典的' }, { p: 'n.', c: '经典作品' }], ex: 'This style is a classic.', ec: '这种风格很经典。' },
      { en: 'elegant', ph: '/ˈelɪɡənt/', defs: [{ p: 'adj.', c: '优雅的；雅致的' }], ex: 'She looks elegant in white.', ec: '她穿白色看起来很优雅。' },
      { en: 'stylish', ph: '/ˈstaɪlɪʃ/', defs: [{ p: 'adj.', c: '时尚的；有格调的' }], ex: 'The shop has stylish bags.', ec: '这家店有时尚的包包。' },
      { en: 'design', ph: '/dɪˈzaɪn/', defs: [{ p: 'n.', c: '设计；图案' }, { p: 'v.', c: '设计' }], ex: 'I like the design of this vase.', ec: '我喜欢这个花瓶的设计。' },
      { en: 'material', ph: '/məˈtɪriəl/', defs: [{ p: 'n.', c: '材料；布料' }], ex: 'What material is this made of?', ec: '这是什么材料做的？' },
      { en: 'size', ph: '/saɪz/', defs: [{ p: 'n.', c: '尺码；大小' }], ex: 'Do you have this in my size?', ec: '有我这个尺码的吗？' },
      { en: 'fit', ph: '/fɪt/', defs: [{ p: 'v.', c: '合身；适合' }, { p: 'n.', c: '合身' }], ex: 'These shoes fit perfectly.', ec: '这双鞋非常合脚。' }
    ]
  },
  19: { // Day19 社交进阶
    topic: '社交进阶',
    words: [
      { en: 'invitation', ph: '/ˌɪnvɪˈteɪʃn/', defs: [{ p: 'n.', c: '邀请；请柬' }], ex: 'Thank you for the invitation.', ec: '谢谢你的邀请。' },
      { en: 'attitude', ph: '/ˈætɪtuːd/', defs: [{ p: 'n.', c: '态度；看法' }], ex: 'She has a positive attitude.', ec: '她态度很积极。' },
      { en: 'relationship', ph: '/rɪˈleɪʃnʃɪp/', defs: [{ p: 'n.', c: '关系；联系' }], ex: 'We have a good relationship.', ec: '我们关系很好。' },
      { en: 'respect', ph: '/rɪˈspekt/', defs: [{ p: 'v.', c: '尊重；尊敬' }, { p: 'n.', c: '尊重' }], ex: 'Respect others\' opinions.', ec: '尊重别人的意见。' },
      { en: 'honest', ph: '/ˈɑːnɪst/', defs: [{ p: 'adj.', c: '诚实的；坦率的' }], ex: 'Be honest with your friends.', ec: '对朋友要诚实。' },
      { en: 'trust', ph: '/trʌst/', defs: [{ p: 'v.', c: '信任；信赖' }, { p: 'n.', c: '信任' }], ex: 'I trust her completely.', ec: '我完全信任她。' },
      { en: 'support', ph: '/səˈpɔːrt/', defs: [{ p: 'v.', c: '支持；帮助' }, { p: 'n.', c: '支持' }], ex: 'Thanks for your support.', ec: '谢谢你的支持。' },
      { en: 'advice', ph: '/ədˈvaɪs/', defs: [{ p: 'n.', c: '建议；忠告' }], ex: 'Let me give you some advice.', ec: '我给你一些建议吧。' },
      { en: 'opinion', ph: '/əˈpɪnjən/', defs: [{ p: 'n.', c: '意见；看法' }], ex: 'In my opinion, it is a good idea.', ec: '在我看来这是个好主意。' },
      { en: 'agreement', ph: '/əˈɡriːmənt/', defs: [{ p: 'n.', c: '同意；协议' }], ex: 'We reached an agreement.', ec: '我们达成了一致。' },
      { en: 'argument', ph: '/ˈɑːrɡjumənt/', defs: [{ p: 'n.', c: '争论；争吵' }], ex: 'They had an argument about money.', ec: '他们为钱吵了一架。' },
      { en: 'forgive', ph: '/fərˈɡɪv/', defs: [{ p: 'v.', c: '原谅；宽恕' }], ex: 'Please forgive my mistake.', ec: '请原谅我的错误。' },
      { en: 'apologize', ph: '/əˈpɑːlədʒaɪz/', defs: [{ p: 'v.', c: '道歉；认错' }], ex: 'You should apologize to her.', ec: '你应该向她道歉。' },
      { en: 'promise', ph: '/ˈprɑːmɪs/', defs: [{ p: 'v.', c: '承诺；答应' }, { p: 'n.', c: '承诺' }], ex: 'I promise to call you.', ec: '我保证给你打电话。' },
      { en: 'behave', ph: '/bɪˈheɪv/', defs: [{ p: 'v.', c: '表现；举止' }], ex: 'The kids behaved well at dinner.', ec: '孩子们晚餐时表现很好。' },
      { en: 'manner', ph: '/ˈmænər/', defs: [{ p: 'n.', c: '礼貌；方式' }], ex: 'He has good table manners.', ec: '他餐桌礼仪很好。' },
      { en: 'gentleman', ph: '/ˈdʒentlmən/', defs: [{ p: 'n.', c: '绅士；先生' }], ex: 'He is a true gentleman.', ec: '他是一位真正的绅士。' },
      { en: 'lady', ph: '/ˈleɪdi/', defs: [{ p: 'n.', c: '女士；淑女' }], ex: 'The lady at the desk helped us.', ec: '前台那位女士帮了我们。' },
      { en: 'couple', ph: '/ˈkʌpl/', defs: [{ p: 'n.', c: '夫妻；一对' }], ex: 'The couple next door is friendly.', ec: '隔壁那对夫妻很友好。' },
      { en: 'companion', ph: '/kəmˈpænjən/', defs: [{ p: 'n.', c: '同伴；伙伴' }], ex: 'She is a pleasant travel companion.', ec: '她是个愉快的旅行同伴。' }
    ]
  },
  20: { // Day20 工作与学习
    topic: '工作与学习',
    words: [
      { en: 'career', ph: '/kəˈrɪr/', defs: [{ p: 'n.', c: '职业；事业' }], ex: 'She is building a career in teaching.', ec: '她正在从事教职事业。' },
      { en: 'manage', ph: '/ˈmænɪdʒ/', defs: [{ p: 'v.', c: '管理；设法做到' }], ex: 'He manages a small hotel.', ec: '他经营一家小旅馆。' },
      { en: 'effort', ph: '/ˈefərt/', defs: [{ p: 'n.', c: '努力；尝试' }], ex: 'Learning takes time and effort.', ec: '学习需要时间和努力。' },
      { en: 'achieve', ph: '/əˈtʃiːv/', defs: [{ p: 'v.', c: '实现；达到' }], ex: 'You can achieve your goal.', ec: '你能实现你的目标。' },
      { en: 'improve', ph: '/ɪmˈpruːv/', defs: [{ p: 'v.', c: '提高；改进' }], ex: 'Practice will improve your English.', ec: '练习会提高你的英语。' },
      { en: 'skill', ph: '/skɪl/', defs: [{ p: 'n.', c: '技能；技巧' }], ex: 'Speaking is an important skill.', ec: '口语是一项重要技能。' },
      { en: 'knowledge', ph: '/ˈnɑːlɪdʒ/', defs: [{ p: 'n.', c: '知识；学问' }], ex: 'She has deep knowledge of art.', ec: '她对艺术有很深的了解。' },
      { en: 'experience', ph: '/ɪkˈspɪriəns/', defs: [{ p: 'n.', c: '经验；经历' }], ex: 'Travel is a great experience.', ec: '旅行是一种很棒的经历。' },
      { en: 'interview', ph: '/ˈɪntərvjuː/', defs: [{ p: 'n.', c: '面试；采访' }], ex: 'She has a job interview today.', ec: '她今天有场求职面试。' },
      { en: 'salary', ph: '/ˈsæləri/', defs: [{ p: 'n.', c: '薪水；工资' }], ex: 'The salary is paid monthly.', ec: '薪水按月发放。' },
      { en: 'position', ph: '/pəˈzɪʃn/', defs: [{ p: 'n.', c: '职位；位置' }], ex: 'He applied for a new position.', ec: '他申请了一个新职位。' },
      { en: 'colleague', ph: '/ˈkɑːliːɡ/', defs: [{ p: 'n.', c: '同事' }], ex: 'My colleagues are very helpful.', ec: '我的同事们很帮忙。' },
      { en: 'teamwork', ph: '/ˈtiːmwɜːrk/', defs: [{ p: 'n.', c: '团队合作' }], ex: 'Good teamwork gets things done.', ec: '良好的团队合作能成事。' },
      { en: 'goal', ph: '/ɡoʊl/', defs: [{ p: 'n.', c: '目标；进球' }], ex: 'Set a small goal every day.', ec: '每天定一个小目标。' },
      { en: 'challenge', ph: '/ˈtʃælɪndʒ/', defs: [{ p: 'n.', c: '挑战' }, { p: 'v.', c: '挑战' }], ex: 'Learning a language is a challenge.', ec: '学一门语言是个挑战。' },
      { en: 'opportunity', ph: '/ˌɑːpərˈtuːnəti/', defs: [{ p: 'n.', c: '机会；时机' }], ex: 'Don\'t miss this opportunity.', ec: '别错过这个机会。' },
      { en: 'practice', ph: '/ˈpræktɪs/', defs: [{ p: 'n.', c: '练习；实践' }, { p: 'v.', c: '练习' }], ex: 'Practice makes perfect.', ec: '熟能生巧。' },
      { en: 'progress', ph: '/ˈprɑːɡres/', defs: [{ p: 'n.', c: '进步；进展' }], ex: 'You are making great progress.', ec: '你进步很大。' },
      { en: 'succeed', ph: '/səkˈsiːd/', defs: [{ p: 'v.', c: '成功；达成' }], ex: 'If you try hard, you will succeed.', ec: '只要努力，你就会成功。' },
      { en: 'ability', ph: '/əˈbɪləti/', defs: [{ p: 'n.', c: '能力；才能' }], ex: 'She has the ability to lead.', ec: '她有领导能力。' }
    ]
  }
};
